### ISSUE TITLE
SSL error only when loaded via WPT

### ISSUE THREAD

**Issue by inian** [WPO-Foundation/webpagetest#1073]
When I load https://www.mtn.com/en/Pages/default.aspx directly on Firefox, it loads fine. But when I load it via WPT Firefox, it throws an SSL error - https://www.webpagetest.org/result/171220_MN_56781d0e2ae610f53cb0718bd2673258/ 

Appreciate any help on how can I go about debugging this,

Thanks!

**Comment by pmeenan** [comment]
Looks like you are missing the intermediate certificate for your CA so the full chain isn't available.  It works in local testing because some other site served the intermediate cert so it is in the OS cache.  Not sure if [this](https://knowledge.geotrust.com/support/knowledge-base/index?page=content&id=INFO1421) is the right one but it looks like your root is Geo Trust.

SSL Labs test is a good place to test for cert issues:
https://www.ssllabs.com/ssltest/analyze.html?d=www.mtn.com&hideResults=on&latest

![image](https://user-images.githubusercontent.com/444165/36272302-1fa64798-124f-11e8-88e2-7567bfd09781.png)
