### ISSUE TITLE
jsonResult.php is not returning full results

### ISSUE THREAD

**Issue by rdejuana** [WPO-Foundation/webpagetest#1079]
I am running a private instance and when I fetch the results from jsonResult.php?test=<testid>

I am getting
```
{
data: {
html_result_url: "http://<domain>/results.php?test=180102_GG_KT"
},
statusCode: 200,
statusText: "Test Complete",
webPagetestVersion: "17.12"
}
```

**Comment by rdejuana** [comment]
The test ran and I am able to fetch it

![Uploading SS 2018-01-03 at 8.09.41 AM.png…]()

**Comment by pmeenan** [comment]
There was an issue for a few hours yesterday but it was [fixed in the afternoon](https://github.com/WPO-Foundation/webpagetest/commit/338535f4c50b69e5ff8f6b03a051016b4bdf247a).  If you are using the server AMI it should have picked up code fixes within an hour and shouldn't still be having issues.  If it is you can try a forced update by visiting http://<domain>/cron/hourly.php

**Comment by rdejuana** [comment]
done, but it still seems to be broken

**Comment by pmeenan** [comment]
Is it running the ec2 server AMI or your own deployment?  May need to go into the server directory and "git pull origin master" to be sure

**Comment by rdejuana** [comment]
its an ec2 server AMI

**Comment by rdejuana** [comment]
I was able to git pull from the server and its seems to be working
