### ISSUE TITLE
Calrification about TTI

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/webpagetest#1087]
Hey,

the [TTI docs](https://github.com/WPO-Foundation/webpagetest/blob/master/docs/Metrics/TimeToInteractive.md) say that it starts looking for the interactive window after firstContentfulPaint.

However, in the code it looks like we also look for domContentLoaded, if either render or firstContentfulPaint occured before:
https://github.com/WPO-Foundation/webpagetest/blob/def93b40d53365f1b3a06d3674f97fbb0e9d9c08/www/page_data.inc#L272-L274

So the actual logic is "look for contentfulPaint or render time. Use the max of this and domContentLoaded to start looking for an interactive window", right?

Why doesn't domContentLoaded matter if no render/contentfulPaint is set?

Thanks :)

**Comment by pmeenan** [comment]
Updated the docs, thanks for reminding me.  TTI is evolving as the Lighthouse team experiments with it and they have moved to using the max of FCP and DCL (caught a few edge cases).

As far as DCL not mattering when FCP isn't set - it's not that DCL doesn't matter, it's that the TTI isn't calculated at all in that case because it needs a start render as an anchor.
