### ISSUE TITLE
Can't run agent successfully

### ISSUE THREAD

**Issue by cpselvis** [WPO-Foundation/webpagetest#1091]
![image](https://user-images.githubusercontent.com/18289264/35149050-a54b872e-fd4f-11e7-9873-c84e7c71b28a.png)

![image](https://user-images.githubusercontent.com/18289264/35149281-75b5841e-fd50-11e7-92f2-ee1512597daa.png)

After install apache2 and webpagetest server on my local mac osx, and I start to run agent.

```
$ cd webpagetest
$ cd js/agent
$ ./wptdriver.sh
```

Got error, the error log is: Jan_19_19:22:32.408 wpt_client.js:563 Client.<anonymous> : Got error: connect ECONNREFUSED 127.0.0.1:8888

Really need your help.

**Comment by pmeenan** [comment]
The js agent has been deprecated for at least the last year.  You should be using [wptagent](https://github.com/WPO-Foundation/wptagent) instead.

That said, the issue you are seeing specifically is because of the location ID's.  It doesn't look like you have configured locations.ini on the server or it just doesn't match the location ID you are using on the agent ("Test" on the agent - the ID's on the server look like they are "IE", "Chrome", "Firefox", "Android_Chrome" and "ios_Chrome")

**Comment by cpselvis** [comment]
OK, I'll try wptagent and give you feedback later.

**Comment by cpselvis** [comment]
After using [wptdriver](https://github.com/WPO-Foundation/wptagent), project get works. The running scripts is:
```
$ python wptagent.py -vvvv --server http://127.0.0.1/work/ --location WPT_Chrome
```


Close this issue.
