### ISSUE TITLE
Webpagetest measures performance numbers before network request is fulfilled

### ISSUE THREAD

**Issue by sarathnairck12** [WPO-Foundation/webpagetest#1104]
I am running a scripted instance on webpagetest chrome browser. Details of the test here: http://www.webpagetest.org/results.php?test=180208_NG_c9460c56da0b8d694f8cecaa94b772f3

As you can see from step 2, the performance numbers are captured before the page is completely loaded. From the request waterfall (http://www.webpagetest.org/result/180208_NG_c9460c56da0b8d694f8cecaa94b772f3/1/details/#waterfall_view_step2), request 30 is not complete. Seems like wpt is not waiting for the request to complete. I even tried adding DOMElement to the script, still it doesn't work. No matter what value I set for DOMElement it neither works nor times out. Is there any workaround for this issue?

**Comment by pmeenan** [comment]
Try using the [setActivityTimeout](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-setActivityTimeout) script command to increase the required idle time before it calls a test done.

WPT doesn't wait for pending requests to finish, it just looks at network activity after onload and if something takes longer than 2 seconds it considers it idle.  Otherwise the pattern of long-polling would cause serious issues.  Using a 10-second activity timeout usually fixes the issue for slow-responding servers.

**Comment by pmeenan** [comment]
Make sure to put the setActivityTimeout command before the step in the script where you want it to take effect.

**Comment by sarathnairck12** [comment]
Setting setActivityTimeout seemed to fix the issue. Is there any way I can use DOMElement to get around this issue because we don't need to wait the extra time if activity is completed before the timeout value? Anyways I am marking the issue as fixed. Thanks!
