### ISSUE TITLE
Start Render and Visually Complete missing from Samsung Galaxy 5 and 6 

### ISSUE THREAD

**Issue by abhagupta** [WPO-Foundation/webpagetest#1154]
There are times when we do not see Start Render and Visually Complete from some of the Samsung Galaxy devices that we have hooked on to a private instance.  Can you think of any reason why? And how can we troubleshoot?

**Comment by pmeenan** [comment]
If it is intermittent with the same test settings then if you run the tests with keepvideo=1 as a raw test option you can have the video recorded on the device of the page load and see if there was something wrong with the video capture.  It's possible a popup blocking the screen or something similar caused it to fail to detect the viewport.

What agent are you using (old nodejs agent or the python agent)?  If it is the older agent then it's possible that video capture isn't enabled for some of the tests since the visual metrics are only available with video capture (the newer agent always captures video).

**Comment by abhagupta** [comment]
It is python agent.. and yes, after passing video=1 we could see the Start Render and Visual Complete. thanks again.
