### ISSUE TITLE
Missing test data on repeat views

### ISSUE THREAD

**Issue by rdejuana** [WPO-Foundation/webpagetest#1159]
I'm seeing missing test data on repeat views.

I tested rdejuana.wpengine.com.  Its a basic site, but it used to test just fine.  Now it fails to get the repeat view.  

I tested on my personal instance and on the public instance of WPT

https://www.webpagetest.org/result/180709_RE_c0985d5321449c58a2a3ce63eb54f5b3/

**Comment by pmeenan** [comment]
I think the issue is that the repeat view is 100% served from cache (including the html which has a 5-minute cache lifetime).  Generally WPT needs network activity to be able to measure the start/end of a test.  I'll see if there's anything I can tweak to get it to work with the cached requests.  The waterfall will be completely empty but you'd at least get useful visual metrics.

**Comment by rdejuana** [comment]
Cool, that makes sense.  We cache the hell out of our sites

**Comment by pmeenan** [comment]
Should basically be fixed now but it will take the agents up to an hour to pick up the change.  [Here is a test with the fix](https://www.webpagetest.org/result/180709_QX_7e8ca7a06e9a98ab2dc2e5665d09cf33/) from my dev environment.

Fully loaded could probably be fixed to match the onload time (will probably do that now).  Plumbing through the from-cache first-byte time will be quite a bit more complicated though at some point I want the waterfall to be able to show cached requests and serviceworker-served responses as well (just not sure I want to tackle it yet).

**Comment by pmeenan** [comment]
Now with the [fixed fully loaded time as well](https://www.webpagetest.org/result/180709_CX_22fed69e34ff9a8acee6f7908ae40846/).  Let me know if there is something else you'd like to see for pages served entirely from cache or if any of the other metrics don't work.
