### ISSUE TITLE
DNS time of 0ms on initial request

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/webpagetest#1185]
[This test on public](http://www.webpagetest.org/result/180916_Q8_9b7d66a10f1612671907d986ffc822e9/1/details/#step1_request1) has a DNS time of 0ms for the initial HTML request which doesn't seem possible if the DNS cache has been cleared. Any idea why this is happening @pmeenan? HTTP/2 related?

<img width="1031" alt="screen shot 2018-09-17 at 9 44 23 am" src="https://user-images.githubusercontent.com/204268/45601283-c6373880-ba5e-11e8-8a2d-d80901bc484b.png">

**Comment by jpenston** [comment]
Hi Pat - I was the person who notified Mark of the issue. We run about 5k tests a day and before 25th July, there were a very small number with this problem.

After that day, we suddenly started seeing about 15% of tests are returning 0 _dns_ms time for the root page. I think the problem is with _dns_start because _dns_end looks right, but _dns_start = _dns_end in the problem tests.

Then on 4th September, about 85% of our tests started returning 0.

We still see some that are ok, eg https://speedcurve.com/j-j/consumer-new/test/180917_R5_1ae5501eabce0b229d12d0bc09a22994

**Comment by pmeenan** [comment]
I've been looking at some raw netlogs from Chrome and I'm seeing cases with it as well where it doesn't look like the DNS lookup for the base page goes through the normal path and mostly isn't logged.  Then there's a followup request for the actual navigation that is returning a "cache hit" (from Chrome's internal cache).

I just pushed some fixes to try to improve it but I'm still seeing cases with "0" DNS timings.  I'm also seeing the DNS lookup happen in the tcpdump so I know it's not cached at the OS level.
