### ISSUE TITLE
Chunks in Firefox seems sometimes be a little bit off

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#1188]
Hi Patrick,
thanks for the chunks in the waterfalls, it's great!

I think maybe for Firefox it seems that they are a little bit off in the waterfall, it looks like the response ends and then it comes again:
<img width="806" alt="screen shot 2018-09-24 at 9 51 17 am" src="https://user-images.githubusercontent.com/540757/45941626-6a7d2a00-bfdf-11e8-985b-8bb83ce5dfff.png">

http://wpt.wmftest.org/result/180924_JY_5M/1/details/#waterfall_view_step1

Or am I reading it wrong? I guess it's Firefox that reports them wrong the HTTP log or could it be that the end timings for each response is wrong?
Best
Peter

**Comment by pmeenan** [comment]
Has to be a bug in the processing somewhere because the same timestamps are used for the end of the bars themselves.  I'll take a look and see what's going on (may be a day or two before I get a chance).  It's either going to be that the bars should really be extended to include the chunks or the chunks should be left-shifted (I'm thinking it's a problem with the bars, not the chunks).

**Comment by pmeenan** [comment]
Should be [fixed now](https://github.com/WPO-Foundation/wptagent/commit/b43ab6521fb9c405f03f34cbace93bd5b7cbdc82) (will take up to an hour to roll out).  The chunk timings weren't being adjusted to a new start time while the other timings were.

Looks like the connection view [may be broken and is missing the base page requests](https://www.webpagetest.org/result/180925_RE_d64d909848a6629498ad62d14af87a4a/1/details/#connection_view) (separate problem).

**Comment by pmeenan** [comment]
Chunks are fixed for Firefox now and the connection view works correctly for HTTP/2 with coalesced connections: https://www.webpagetest.org/result/180925_KZ_645a1718809e601a02a799efe9e877b0/1/details/#waterfall_view_step1
