### ISSUE TITLE
All score_ metrics return -1 (are missing) in Firefox runs

### ISSUE THREAD

**Issue by stephendonner** [WPO-Foundation/webpagetest#1199]
All of the various ```score_```[```cache``` ```cdn``` ```gzip``` ```cookies``` ```keep-alive``` ```minify``` ```combine``` ```compress```]``` metrics are showing up as ```-1```, with Firefox: https://www.webpagetest.org/result/180930_AD_e4fc6b8cf6c0f61410efdd12944605be/?f=json

Also worth noting (and probably the source of the issue?) is that ```gzip_save``` and ```gzip_total``` are ```null`.

**Comment by pmeenan** [comment]
Most of the scores require access to the response bodies which aren't captured on Firefox.

________________________________

**Comment by stephendonner** [comment]
Hrm; although I haven't run my older wptscript + testspecs.json-style asserts in Jenkins for a while, it used to work quite well, at least for the 3 score_ metrics I chose then: https://github.com/stephendonner/webpagetest-amo/blob/8c666cd01ec93b5c8073b95776efa3de02f502b6/homepage-testspecs.json#L14

**Comment by pmeenan** [comment]
It used to work with wptdriver on windows which hooked the networking stack API calls to get the raw streams. Wptagent doesn't do that. I experimented with getting the bodies from the extension using the webextension streaming response but at the time it didn't work for images and added a bunch of overhead. Haven't tried again since.

________________________________

**Comment by stephendonner** [comment]
Thanks, Pat; I continue to vet and bring back WebPageTest <---> Firefox co/inter-dependencies, etc., to help prioritize fixes and features from our side, so I'll add this.
