### ISSUE TITLE
adding custom cdn

### ISSUE THREAD

**Issue by nstiac** [WPO-Foundation/webpagetest#1256]
Ok, so we have a couple houndred websites and have developed our own CDN network, how do we go about adding this to cdn.h ?

**Comment by pmeenan** [comment]
The current CDN detection is done in [wptagent here](https://github.com/WPO-Foundation/wptagent/blob/master/internal/optimization_checks.py#L48). If you provide the details (specific header or CNAME that can be used to identify it) and some example tests for a site using it I can take care of adding it.

The main thing with a semi-private CDN is that it needs to be globally distributed with traffic routed to the closest edge to be considered for WebPageTest's CDN detection (not just a separate set of static content servers in one region). As long as that is the case, adding it won't be a problem.

**Comment by ywarnier** [comment]
Hi @pmeenan

Could I suggest an form input in the "Advanced" section to just enter the domains of our custom CDNs?
This would mainly be a change to add those custom CDNs to self.cdn_cnames in https://github.com/WPO-Foundation/wptagent/blob/master/internal/optimization_checks.py#L62 somewhere before they are checked here: https://github.com/WPO-Foundation/wptagent/blob/c2fddea669140dfd7f42ce8b2ff90953059ca3b3/internal/optimization_checks.py#L724 ...

**Comment by chris-kruining** [comment]
> Possibly for a private instance but I wouldn't be comfortable doing that for the public instance. It feels like it would be too easy to game when sharing results with others.

easy to game indeed, but now I am loosing score for nothing. plus the fact that cdn's became nearly irrelevant with the new stricter site isolation. The new advise is to host all resources on the same domain as it also saves on the overhead of additional tcp connections.

**Comment by pmeenan** [comment]
FWIW, nobody is "losing score". You're either using a CDN or not and it will show you with a check or an X respectively. If you're not using one and have a good reason not to be then great, it's as expected.

It's important to note that WebPageTest it's recommending a CDN so you'll use a shared static CDN for jquery or something like that.  The BEST way to use a CDN is to host your main domain on the CDN.  They will pass dynamic requests back to the origin and serve static content from the edge, all transparently. They usually also have benefits for dynamic content since they lower the RTT to the end user (connection setup is faster, TCP slow start ramps quicker, etc) and they usually have well tuned networking stacks.
