### ISSUE TITLE
Hero Element Times is hanging agents

### ISSUE THREAD

**Issue by pmeenan** [WPO-Foundation/webpagetest#1262]
Enabled heroElementTimes=1 on the public WebPageTest and agents started dropping offline intermittently and appeard to be hung at the end of video processing.

**Comment by pmeenan** [comment]
@wildlyinaccurate FYI

**Comment by pmeenan** [comment]
They all looked very similar to this:

![image](https://user-images.githubusercontent.com/444165/55026249-04e31800-4fd9-11e9-9b85-e27534888d51.png)

**Comment by wildlyinaccurate** [comment]
Huh, that's weird. By this point it has already calculated the render times and cleared up any temporary files. I'm guessing there's a child process still running somehow, otherwise I don't see why it would hang at this point.

Was there any pattern in the agents or test URLs that might help me replicate this?

**Comment by pmeenan** [comment]
I'll see if I can reproduce it.  Was mostly worried about bringing the agents back online so I was rebooting everything and didn't gather test ID's.

**Comment by wildlyinaccurate** [comment]
I can't reproduce the issue so taking a stab in the dark here, but I dug up [this comment](https://bugs.python.org/msg142485) on an old [bug report for Python 2.7](https://bugs.python.org/issue12786). Is it possible that due to some difference in settings between your agents and mine, your agents have an open file descriptor when visualmetrics.py is forked, causing a sort of deadlock?

**Comment by wildlyinaccurate** [comment]
Actually rather than stabbing in the dark, if you could send me your settings.ini (minus any sensitive info) I can try to reproduce on my agents. joseph at speedcurve dot com.

**Comment by pmeenan** [comment]
Checking to see if I can reproduce it. I might also see what impact using close_fds might have and/or moving the visualMertics check into a thread and called directly instead of running it as a separate process.

**Comment by pmeenan** [comment]
I can reproduce it pretty reliably after ~10-20 tests. Not sure if it is URL-specific or just a leak or random timing.

I put a bunch of exception handling into the hero timings calculation (around where it removes the mask files) in case any of the mash removals is throwing an exception mid-processing (though not sure why that would hang it). So far it is looking more stable in my test VM but I'm going to hammer on it a bunch more to make sure and then try it in prod again.

**Comment by wildlyinaccurate** [comment]
Turns out when we enabled hero timing on the SpeedCurve agents, our failed tests increased by 300%. At our scale of testing we didn't really notice it since we automatically kill the problem agents, spin up new ones, and re-run the failed tests.

That latest commit didn't noticeably reduce our error rates, so I'll keep poking around on my local agent.

**Comment by pmeenan** [comment]
Not positive the last set of changes fixed it but it has been running for a few hours on my test machine without a hang.  Going to let it run for a while longer before calling it good and flipping the flag on the public instance

**Comment by pmeenan** [comment]
Test VM went through a few thousand tests without hanging with the latest agent code so I'm feeling pretty good about it.  I just flipped the flag on for the public instance and I'll keep an eye on things to make sure the agents don't get stuck and go offline.

**Comment by pmeenan** [comment]
So far it looks stable on production. @wildlyinaccurate does it look like your failed rates dropped?

**Comment by wildlyinaccurate** [comment]
@pmeenan yes, it does look that way! Thanks very much.
