### ISSUE TITLE
Add download chart to waterfall?

### ISSUE THREAD

**Issue by bazzadp** [WPO-Foundation/webpagetest#1320]
Have you ever thought about adding a download chart, similar to the "Browser Main Thread" or "Page is interactive" charts? I thought it used to have something like this but maybe I imagined it...

This would show the amount being downloaded across all connections - and more importantly where there are large gaps when nothing is being downloaded (because it's waiting on connection establishment, or back end processing, or JavaScript is executing to give next set of assets...etc.).

Ideally it would be a percentage of available bandwidth but that might be quite complicated to estimate, so maybe percentage of maximum download. e.g. at one point 6 connections downloaded 50 kbps and that was maximum so that's your top Y gradient, and 0 is your bottom, so then measure everything based off of that.

Thoughts?

**Comment by pmeenan** [comment]
![image](https://user-images.githubusercontent.com/444165/71420325-a4a20500-2642-11ea-9191-5e7aaa1902bd.png)

It's already there ("Bandwidth").  For tests with pre-configured connectivity it is capped at the configured bandwidth, otherwise it estimates it based on the peak data.

![Screen Shot 2019-12-24 at 11 29 12 AM](https://user-images.githubusercontent.com/444165/71420032-e2059300-2640-11ea-93f5-d1f15bbf904e.png)

It should be there by default for all desktop agents (including mobile emulation).  For mobile devices you need to enable tcpdump capture to get it (bonus, for the tcpdump version, it shows goodput and spurious retransmits):

![Screen Shot 2019-12-24 at 11 51 16 AM](https://user-images.githubusercontent.com/444165/71420532-bb952700-2643-11ea-91d0-896190269334.png)

The timings might not align perfectly with the waterfall but they should be close.

**Comment by bazzadp** [comment]
Thanks @pmeenan - I knew I’d seen it before. Need to get used to living in this mobile first world 😀
