### ISSUE TITLE
Chrome might not be up-to-date on agent instances

### ISSUE THREAD

**Issue by gfx** [WPO-Foundation/webpagetest#1326]
I use private instances on GCP, and found that Chrome, including Beta and Canary, might not be up-to-date. Curious because other browsers, e.g. Firefox, is up-to-date on the same agent instances.

I've found this issue today and am investigating it. Do you have any information about it?

**Comment by pmeenan** [comment]
The agents automatically apt-update at startup but there's a chance Google's signing keys changed since the original images were created.  I'll see if I can create new images but if so you'll have to update your instance templates (re-run the agent part of the GCE setup script).

You can also create your own images using a Ubuntu base image and the GCE setup script: https://github.com/WPO-Foundation/wptagent-install#on-google-cloud

**Comment by pmeenan** [comment]
I created a new master image that is both up to date and also installs the current signing keys at startup so it should stay current (though there will be a new one in a few months that uses python3 instead of 2.7).

You'll need to re-generate your instance templates to use the new image: https://github.com/WPO-Foundation/webpagetest-docs/blob/master/user/Private%20Instances/gce_agents.md

**Comment by gfx** [comment]
I see. Re-created the instance template and it works well. Thank you!
