### ISSUE TITLE
S3 Archive high amount of requests for idle system

### ISSUE THREAD

**Issue by bramevo** [WPO-Foundation/webpagetest#1340]
We are the 2nd of the month and I already have 1,721 Requests (Put, Copy, Post or List Requests of Amazon S3) while I ran 0 tests this month and only have 102 old zipped tests in S3 bucket till now.

So I would assume there is some inefficiency in the way webpagetest uses S3.
Relevant items in settings.ini file:
archive_days=15
cron_archive=1
I'm not using archive_s3_url because it was giving issues for some unknown reason.
Running the Docker server and agent on AWS ECS. Also have a mounted EFS volume for HA purposes.

Thinking about just disabling the S3 archive feature because of this, although I like the idea of it.
Anyone noticed the same problem?

**Comment by pmeenan** [comment]
Do get requests get counted as well?  Do you have anything polling the server for test results, a site search crawling them or something similar (access log on the web server should show).  Do you have any way to see where the S3 requests are coming from (i.e. is it ACL'd to only allow access from the server or is something external scanning?

When a test is accessed, if it isn't available locally because it has been archived it will pull the archived test down and cache it locally.  That said, it shouldn't delete the local cached copy until it is time to archive again so at most each test would only be restored twice in a given month (assuming the code is working correctly).

**Comment by bramevo** [comment]
Checked and the Get requests are counted separately: 
Amazon Simple Storage Service Get Requests of Amazon S3: 1,725 Requests
A bit odd that the number is almost identical...

I did activate S3 bucket paid metrics to figure out what the behavior is if I disable the archive cron and enable it again. I hope it will show some kind of graph to compare the numbers.

Maybe it has something to do with the data being on a mounted volume (NFS)?

**Comment by pmeenan** [comment]
As long as the mounted volume is configured as an archive directory and not the main results directory then WPT should have the same behavior (just read when restoring).  Not sure if mounting as a NFS volume opens it up to any other access patterns from the system (I've never used a S3 bucket NFS-mounted)

**Comment by pmeenan** [comment]
I think the issue with NFS mounting might be that the test restoring logic touches the zip file in the archive when it thinks it is using a local directory: https://github.com/WPO-Foundation/webpagetest/blob/master/www/archive.inc#L198

That's mostly used to be able to tell when archived tests have been last accessed so when the archive is pruned you can choose to keep frequently accessed archived tests.  You can try commenting that out to see if it helps.  If so I can add a setting to not update the freshness of archived tests that are on mounted drives (or just stop doing it)

**Comment by bramevo** [comment]
Further investigation showed no increase in the S3 paid bucket metrics, but overall S3 count still went up. Apparently it was a local docker container that was still running and stuck in a loop doing the S3 request towards another bucket.
So apparently issue was not related to webpagetest.
Will activate S3 archiving again to see what the actual usage is for S3 webpagetest archiving for an "idle" system.
