### ISSUE TITLE
Mobile version loads desktop version images too

### ISSUE THREAD

**Issue by berdini** [WPO-Foundation/webpagetest#1342]
Hi, I realized that when I perform the test on the mobile version my website desktop version images  are being loaded too. I have the "hide on mobile" Elementor function working over my desktop slider so that images are not being loaded for the mobiles. Is there any workaround to simulate the real performance of my website? Many thanks

**Comment by pmeenan** [comment]
Do you have a link to a test result? You can try testing on one of the Moto G4 devices in Dulles to be sure but it's highly unlikely that this is a test problem. 

Hiding images is not enough to get them not to load over the network.

**Comment by berdini** [comment]
Hi,
https://www.webpagetest.org/result/200402_SH_19c4f5cfa474b039a8c7559506cbd1b9/
thanks

**Comment by berdini** [comment]
(Images with the _M_ are Mobile Version hidded in the Desktop and Tablet Versions, and images with _F_ are Desktop Version Full With images hidded for mobile and Tablet versions)

**Comment by pmeenan** [comment]
That is a test on an actual mobile device running the latest actual Chrome stable browser. It's not a testing problem, that is the "real performance" (actually, it is optimistic because it was tested at a "native" speed which is a 300Mbps fiber connection).

Whatever you are trying to do to not serve desktop images is not working and is only hiding them from view but is still downloading them.

You'll need to reach out to Elementor or whoever worked on the page to understand why it isn't working the way you want it to.
