### ISSUE TITLE
Identifying to which TCP connection a request belongs

### ISSUE THREAD

**Issue by jonglezb** [WPO-Foundation/webpagetest#1344]
First, thanks a lot for this excellent tool!

I am trying to exploit the JSON results, and one of my sub-goals is to group requests according to the TCP connection they were sent on.

I figured that I can use the (`host`, `local_port`) tuple to identify the connection of a request.  However, there are some edge cases where it doesn't work:

1. some requests don't have a `local_port`! See request 160 in [this run](https://www.webpagetest.org/result/200413_TR_6b2d0ab625aaded559acd545e25062f0/3/details/). The strange thing is that request 161 does have a `local_port`, while it is the same kind of request (asynchronous API call) to the same server.
2. browsers apparently reuse a connection to the same server even for different names. In the same example as above, request 161 to `api.flickr.com` reuses the same connection as `www.flickr.com` (requests 1 and 158)

Leaving aside the first issue, this second point tells me that I should just use the `local_port` to determine the connection, but it seems brittle. Is there a better way I missed?

**Comment by pmeenan** [comment]
If you look at the "raw details" for any given request it should have a "socket" identifier. That is the best source for identifying which requests were served over the same connection and is used for the connection view.

There may still be some bizarre edge cases where it isn't recorded correctly because of browser reporting but it should be better than the client port.

The client port can work as well but is mostly useful for looking into a given stream in a tcpdump.

**Comment by jonglezb** [comment]
Ah, right, I had completely missed the `socket` field! Many thanks, it works exactly as intended!
