### ISSUE TITLE
Ubuntu 20.04 showing pathological layout times with Chrome

### ISSUE THREAD

**Issue by CheViana** [WPO-Foundation/webpagetest#1410]
This is the problematic run, from 'Dulles, VA - Chrome - Cable':
In https://www.webpagetest.org/ advanced testing, select location 'Dulles USA' and browser Chrome, other settings are defaults
https://www.webpagetest.org/result/201208_Di07_4f766daaedee8da7eb9c20790b02b4d0/
Tester: VM01-02-192.168.199.214
Largest Contentful Paint happens at 4.7 seconds, and it's visible that CPU is busy computing layout

This is run from 'Dulles, VA - Thinkpad T430 - Chrome - Cable' for same target page:
https://www.webpagetest.org/result/201208_DiM5_6608508db5054c56bdc3115b306319ae/
Largest Contentful Paint happens at 1.6 seconds

From 'Virginia USA - EC2 - Chrome - Cable':
https://www.webpagetest.org/result/201208_DiCX_15139a9592dd34e00714fd3d67da3798/
Largest Contentful Paint happens at 1.6 seconds

Before Nov 8 same page LCP from Dulles Chrome was also low https://www.webpagetest.org/result/201108_DiBJ_7905b92298f3bb0dce4a3af87ffab6cf/ Tester: VM05-02-192.168.199.179

Please advice, is this expected? Did device hardware for location Dulles changed on or about Nov 8 2020?

**Comment by pmeenan** [comment]
Definitely not expected.  The servers and VM's in Dulles haven't changed and I don't see any agent code changes that would have impacted it.  Something very pathological is going on between that site, Chrome and that location.

It's not a clock or measurement problem because I see trace events ticking during the operation, the CPU measurements are ongoing and the video matches the waterfall.

It's not timing sensitive and happens no matter the connection speed.

I tried grabbing more detailed traces but it doesn't give a lot more detail - just a giant "PerformLayout" block.

I haven't seen it with other sites but I was able to reproduce it with Chromium on the Raspberry Pi 4: https://www.webpagetest.org/result/201209_Di5B_9837b6f6355d20c71a5e816ea8dbe7cd/

On some other locations it's not as extreme (1-2 seconds) but still looks pretty long.  Blocking the JS doesn't help, blocking the css does reduce it quite a bit but the layout still takes a long time for what should just be plain HTML 

Next steps would probably be to try to reduce it down to a minimal reproduction case and file an issue with the Chrome team (or work around whatever is triggering it).

**Comment by andydavies** [comment]
I got pointed at this site the other day and I'm not sure it's the same issue but it smells similar - https://www.webpagetest.org/result/201209_Di4Z_9b6a1f09394b8d1ccfe793c11b85299a/

For a pretty simple site 600ms seems to be a long time in Layout, it was worse as there was a late injected base64 encoded image but that's gone now

**Comment by CheViana** [comment]
I can reproduce this slowdown also for 'Dulles, VA - Canary - Cable' and 'Dulles, VA - Chrome Beta - Cable'.

Curious thing shows for 'Dulles - WebKit':
https://www.webpagetest.org/result/201209_DiFM_58100c4b71c761e3676f9664626c63ee/1/details/#waterfall_view_step1
Small SVG images download time is huge, also lots of layout computing

What are chromium and browser versions for:
'Dulles, VA - Chrome Beta - Cable'
'Dulles, VA - Canary - Cable'
'Dulles, VA - Chrome - Cable'
'Dulles, VA - Chromium on the Raspberry Pi 4'
'Dulles - WebKit'
'Dulles, VA - Thinkpad T430 - Chrome - Cable'
'Virginia USA - EC2 - Chrome - Cable'

I might be able to get small reproducible case if I know browser software versions.

**Comment by pmeenan** [comment]
If you look at the user agent string in the request data it will show you the version of each.

**Comment by CheViana** [comment]
User agent string for 'Dulles - Chrome - Cable' which has slowdown:
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 PTST/201208.021248

user agent string for 'Dulles - Thinkpad - Chrome - Cable' which has no slowdown:
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 PTST/201208.211219

user agent string for 'Virginia - EC2 - Chrome' which has no slowdown:
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 PTST/201208.021248

Chrome version matches exactly. Only difference I can spot is Thinkpad is Windows (no slowdown), plain Dulles is Linux (with slowdown), but Ec2 is also Linux and has no slowdown. 

also, I looked at Firefox in Dulles and Firefox in EC2:
https://www.webpagetest.org/result/201209_DiA7_c4068d367689da5fb56e323ef2a4034c/1/details/#step1_request
https://www.webpagetest.org/result/201209_Di0M_6ff77ad34735fd6d0df94284b7d33ec5/1/details/#waterfall_view_step1
For Firefox in Dulles it takes 1 second to download some static files from GCP CDN - Time to First Byte: 1208 ms
Firefox in EC2 does that quicker - 400ms
This might be expected and unrelated though

**Comment by pmeenan** [comment]
Experimenting with some VM's on the same server now to see if there is something pathological going on between Chrome, Ubuntu 20.04 and the physical hardware. Most of the EC2 and GCE images are running 18.04

**Comment by pmeenan** [comment]
18.04 looks a LOT better: https://www.webpagetest.org/result/201209_DiTxM6_221050f9b79b5e107d570435e0b871da/

I'll roll out the VM change over the next few hours

**Comment by pmeenan** [comment]
The queues may get a bit long while I'm transitioning the VM's over but all of the 20.04 ones are off now and the first 8 18.04 ones are online so things should be better now: https://www.webpagetest.org/result/201209_DiNC_2d88b4544354c4a9c52d8e5f1377c70c/

I'll keep this open to track the state of 20.04 though (see if it works OK on newer hardware).

**Comment by pmeenan** [comment]
My guess is Spectre mitigations of some kind that need to be disabled.  The host hardware is fairly old and doesn't have hardware support for any of the mitigations which probably makes it an order of magnitude worse.

**Comment by wildlyinaccurate** [comment]
Might not be the same issue given you're seeing a difference between 18.04 and 20.04, but maybe worth mentioning anyway. We had some step changes going from Chrome 84 to 85 (and all versions since). CPU time increased across the board - layout as well as scripting. You can see in this screenshot Chrome 87 (the bottom CPU chart) spends waaay too long in layout:

![Screenshot from 2020-12-10 12-40-22](https://user-images.githubusercontent.com/794263/101702162-38374480-3ae5-11eb-8eb1-73790cb88592.png)

For us the issue manifests simply by upgrading an 18.04 agent to Chrome 85 (without upgrading anything else). The agent running Chrome 87 in that screenshot is running Python 3 on 20.04 and also has the issue. I [opened a crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=1147742) but haven't got around to bisecting yet.

**Comment by pmeenan** [comment]
So far it doesn't look like it is the spectre mitigations (mitigations=off shows the same issue) or dummy Xorg display vs xvfb (they both show the issue).

Running on a beefy VM on a current-gen Core i9 is somewhat better but still more than twice as slow for layout as the older, slow VM.
