### ISSUE TITLE
Clean up custom waterfall form

### ISSUE THREAD

**Issue by tkadlec** [WPO-Foundation/webpagetest#1452]
The form on the custom waterfall page could use a little touch up, both to make it cleaner visually and improve the accessibility.

<img width="1096" alt="Screen Shot 2021-03-19 at 4 23 51 PM" src="https://user-images.githubusercontent.com/66536/111845014-10206400-88d2-11eb-97f0-a54aa98dddb7.png">

**Comment by scottjehl** [comment]
I thought I'd start to tinker with ideas on this issue first. One thing that came to mind for this particular layout is that it might be nice to have the settings in some sort of panel/overlay as real estate allows, so that you can see the changes as you make them, without having to scroll down to see them. Again, just an idea, but on wider viewports, I'm curious what people think of something like this? 


https://user-images.githubusercontent.com/214783/133443234-5d078e2f-416e-4223-9669-d859bd47a4a8.mov

For smaller viewport sizes, assuming we're working towards a small-screen friendlier layout for these pages, maybe it could sit above and toggle open and closed or something.

**Comment by tkadlec** [comment]
I like this a lot! Can we provide a way to toggle the display of the box? So if I make my changes and want to see the full waterfall image, I don't have the box sitting over top?

**Comment by tkadlec** [comment]
Or, maybe alternatively, have the settings box shifted on the bottom instead of the right? 

I dunno. Just thinking of how to make sure we can see the full waterfall image....

**Comment by scottjehl** [comment]
Thanks, @tkadlec. I like that idea, sure thing!

**Comment by scottjehl** [comment]
> I dunno. Just thinking of how to make sure we can see the full waterfall image....

Yeah. I suppose we could just toggle the entire thing too (excuse the in-progress styling)


https://user-images.githubusercontent.com/214783/133488435-864a4cd8-bded-4737-af85-feab353dcf97.mov

**Comment by tkadlec** [comment]
Good call. I like that a lot, @scottjehl

**Comment by scottjehl** [comment]
Quick status update:

https://user-images.githubusercontent.com/214783/133511000-b7ffa235-84c2-4bb8-9ee0-3c6e291373ee.mov
