### ISSUE TITLE
Can't open legacy traceviewer UI from perfetto UI because CSP

### ISSUE THREAD

**Issue by paulirish** [WPO-Foundation/webpagetest#1489]
Repro:  

1. open https://www.webpagetest.org/chrome/perfetto/index.html#!/viewer?url=https%3A%2F%2Fwww.webpagetest.org%2Fgetgzip.php%3Ftest%3D210427_AiDcY5_6b7bf653cefd77cddf478b8184981c7f%26file%3D1_trace.json
2. try opening it in the Legacy UI because sometimes the new perfetto UI is sometimes hard to adopt. :p 
3. Click on ![image](https://user-images.githubusercontent.com/39191/116288089-fe8a7180-a745-11eb-8f47-bdb9e1616557.png) in the sidebar
4. Enable popups for the domain because popupblocker causes some problems.
5. try again
6. The page opens `about:blank` in a new tab, but its never populated.
7. Check console and see:

> `Refused to navigate to 'https://www.webpagetest.org/chrome/perfetto/assets/catapult_trace_viewer.html' because it violates the following Content Security Policy directive: "navigate-to https://*.perfetto.dev".`

The CSP is being set in a `<meta http-equiv="Content-Security-Policy"`. 

![image](https://user-images.githubusercontent.com/39191/116288626-8f614d00-a746-11eb-8cae-6b20740b8226.png)

My quick guess is because this is being rehosted on `https://www.webpagetest.org/`, the `navigate-to` directive also needs a `self`. 

cc @deepanjanroy

**Comment by deepanjanroy** [comment]
Thanks for reporting Paul! 

@primiano @chromy Should we add 'self' navigate-to CSP here? https://source.chromium.org/chromium/chromium/src/+/master:third_party/perfetto/ui/src/frontend/index.ts;l=301;drc=4ed03f206457414bfcd3592afec4a0b3f71d821d

**Comment by pmeenan** [comment]
Thanks.  WPT is running a pretty old copy of perfetto anyway so I need to go in and update (and maybe switch to the supported method for embedding while I'm at it).

I'm updating the embedded inspector right now - will look at perfetto right after.

**Comment by chromy** [comment]
@deepanjanroy makes sense to me, I can send a CL tomorrow unless you get to it first. 😃 

@pmeenan Let me know if you want a hand when changing to the new embedding method.

**Comment by pmeenan** [comment]
Short-term hack, I removed the navigate-to CSP from my copy.  You may have to force-reload to get it to pick up the change in case it cached the previous version but that will buy some time while I change the embedding.

**Comment by primiano** [comment]
>Enable popups for the domain because popupblocker causes some problems.

That, I believem is unfortunately the "engagement tracker" issue.
The problem is that in order for a popup not hit the blocker, the action:
1. needs to be initiated from a user action like a click (which is the case here)
2. need to lead to a window.open within a certain time.

The interesting part is that the "time" variable in 2 is not a constant but depends on how much the browser thinks you "engaged" with the website. The first time is typically conservative, but becomes quite relaxed afterwards.
I can't think of an easy way to solve it. In general the problem goes away after the first visit, so it's probably not worth overthinking it too much.
I am not a fun of this non-reproducible behavior, but I think it's a best-effort mitigation about malicious website that "cache" the user action and reuse it later for an undesired popup.

**Comment by deepanjanroy** [comment]
(Sorry for the tangent discussion; I know this is not the main point of the bug) 

> need to lead to a window.open within a certain time.

1. I'm guessing this won't be a problem if we open a window immediately after the click
2. we can't open the window immediately today because we have a spend a bunch of time converting the trace to json first

Here's an idea for the future: 
1. we first convert the trace to json, and then show a button that says, "click here to open the  legacy viewer"
2. Then we should be able to open the new window instantly after the click
3. pop-up blocker should be happy.

**Comment by primiano** [comment]
Fun fact, now that you mention you reminded me that what you describe is precisely what we do:
if the window.open fails after the conversion, we show another div that promps to click to refresh the gesture:

![image](https://user-images.githubusercontent.com/7137473/116613925-2ab61600-a931-11eb-95a5-daa8f3c07110.png)

So, I cannot tell how we end up hitting the popup blocker actually :/

**Comment by deepanjanroy** [comment]
Ah Pat mentioned the copy of Perfecto UI in WPT is old, so maybe it will be
fixed after it's updated.
