### ISSUE TITLE
Remove Catchpoint paywall for private instance API requests

### ISSUE THREAD

**Issue by cweekly** [WPO-Foundation/webpagetest#1494]
## Feature Request Summary
I was surprised and disappointed and disheartened when the private instance I set up late last year started claiming I needed to update the key for the "enhanced" API. Open source + private instance == should be free! It's extortion.
Not sure how to aim this at Catchpoint (vs WPO-Foundation).

### What's the motivation or use case for the change/feature?
The paywall totally derailed my project at a critical time. 
I don't know if or when I'll be able to convince the client to sign up for a paid subscription. 
$10/mo -- for just 40 tests/day? On my own hardware? Seriously?

**Comment by pmeenan** [comment]
What, specifically, are you talking about?  100% Private instances have their own API keys and don't interact with the Catchpoint infrastructure in any way.

Are you using "relay" locations on your private instance that actually use test agents from the public webpagetest.org?  If that's the case then yes, you will need to purchase API keys to use the Catchpoint test agent infrastructure (because you're not running your own agents and test infrastructure at that point).  If that is the case then you should have received 4-5 emails over the last 2 months at the email address that you used to register for the API key you were using.

If you are running your own private test agents then nothing should have changed.

**Comment by pmeenan** [comment]
Closing this under the assumption that the above assumption about using the API and public test infrastructure through relay is correct.

If you are seeing Catchpoint messages of some kind while using your private server and a location that is using your own test agents (not relay) then please feel free to re-open it and add some more detail.

**Comment by cweekly** [comment]
Hi @pmeenan, thanks for your prompt reply, and for confirming there isn't a Catchpoint paywall for API usage on a private instance. I'm delighted to have been wrong! 

FTR, the confusion stemmed from someone else having updated keys.ini (I'd only checked settings.ini) -- and from the misleading error message when my key didn't match.  
 
`webpagetest test -s <Private-WPT-SERVER-URL> -k <BAD-API-KEY> <URL-TO-BE-TESTED>`  

returns a misleading error message:  
```
{
  "statusCode": 400,
  "statusText": "Invalid API key. To continue running tests via the WebPageTest API,  \
  you'll need to update your current key for the enhanced WebPageTest API.  \
  Read more here: https://product.webpagetest.org/api"
}%
```

^ This message is appropriate for the public instance, but for private instances it should read more like:  
"Invalid API key. To run tests via the WebPageTest API on this private instance, ask the server admin.  \
(Hint: `settings.ini#location_key` (default API key), or `keys.ini#[API Key]` which may override it).  \
Or, use Catchpoint's public instance; see https://product.webpagetest.org/api for details."

**Comment by pmeenan** [comment]
Ahh, thanks.  I updated the message on private instances to not include the Catchpoint bit.  I had kind of assumed that most private instances wouldn't bump into an issue of using invalid keys - probably should have known better.
