### ISSUE TITLE
Consider a future integration to evaluate a site's carbon impact

### ISSUE THREAD

**Issue by scottjehl** [WPO-Foundation/webpagetest#1613]
Thanks to @Nooshu for [the tweet](https://twitter.com/TheRealNooshu/status/1457681398249267200 ). The mentioned service is http://websitecarbon.com  

Happy to discuss potential integration ideas here.

**Comment by scottjehl** [comment]
Follow up https://twitter.com/EcoPingHQ/status/1457690967897739271

**Comment by Nooshu** [comment]
Also worth considering this [JS lib](https://github.com/thegreenwebfoundation/co2.js) that was integrated with [Sitespeed.io](https://www.sitespeed.io/) recently.

**Comment by Nooshu** [comment]
Mockup or a potential integration in the summary for "Sustainability score":

<img width="1104" alt="Screenshot 2021-11-08 at 18 11 26" src="https://user-images.githubusercontent.com/1223960/140795477-0d7ad40c-e112-4c29-ba19-bba611ac2e11.png">

**Comment by fershad** [comment]
The Green Web Foundation provide an API for checking the "green" status for web hosts (used by Website Carbon Calculator as part of their test too). https://www.thegreenwebfoundation.org/green-web-feed/

**Comment by fershad** [comment]
Many of the checks surfaced on the Performance page would be applicable for a "sustainability score".

- Compress transfer
- Compress images
- Leverage browser caching
- Effective CDN use

**Comment by fershad** [comment]
Initial idea of how a sustainability section might look.

![image](https://user-images.githubusercontent.com/27988517/140842526-5dbacfa0-9a63-430f-8ded-e3e148cfbc05.png)

**Comment by rposbo** [comment]
We can pull greenhouse into the lighthouse score and display it in the WPT UI reasonably easily, if that helps:

https://www.robinosborne.co.uk/2020/01/07/customized-webpagetest-lighthouse-results-using-a-custom-test-agent/

https://calendar.perfplanet.com/2019/eco-worriers-saving-the-planet-one-unoptimized-website-at-a-time/

**Comment by shaneniebergall** [comment]
Love this idea, and am excited it seems to have [Tim's support](https://twitter.com/tkadlec/status/1458138407331241990?s=20).

@fershad your render is great. I'm also wondering if any of these metrics should be considered?
 - Browser energy (cpu cycles)
 - Color / screen energy (black > white)
 - CO2e of datacenter vs network

**Comment by screenspan** [comment]
What a great feature request! 💪🏽🌱  I'd love to help out with this topic!

A couple of thoughts:

### Be clear about what the numbers are based on – and link to sources
At the risk of muddying up @fershad 's cool mockup and being a drag, it might be a good idea to provide an estimate range for CO₂e – or at least a **link to an explainer** about what the estimates are based on and what the sources are. The problem is: the energy coefficient (kilowatt hours per gigabyte) depends upon which information sources you use. [Websitecarbon currently uses 1.8 kWh/GB](https://www.websitecarbon.com/how-does-it-work/), although it's used higher estimates in the past. I've also spoken to Tom Greenwood (creator of the Website Carbon Calculator) who told me they'll probably update those estimates due to newer research. Gerry McGovern (author of "World Wide Waste", 2020) uses 0.015 kWh/GB. And I've seen others use numbers in between that.

### The Sustainability Score should help drive actionable change
There are some great ideas in the previous comments. It'll certainly be tricky to define some sort of "Sustainability Score", and in the end, the results should help drive actionable change. 
To that end, I'd suggest **weighing factors for highest impact** (i.e. better score), e.g.
- Byte for byte, JS is more energy-intensive than images. So pages with more JS than images should have worse scores.
- Byte for byte, video is more energy-intensive than images. So pages with more video than images should have worse scores.
- Low 3P bytes has more impact than the % of 3P green-hosted domains. So pages with low 3P byte counts should have better scores than pages with a large number of 3P bytes even when they're green-hosted.

### Explainer page
As mentioned above, we'd need an Explainer page containing info about:
- How the sustainability audit works
- How the sustainability score is calculated
- Links to more resources
- That the audit applied to the part of the page tested (can of course differ for scripted tests where cookies are accepted or the page is scrolled to the bottom)

### Display the 'Carbon Cost' in the table on the Test Results page
Currently on the Test Results page in the Summary view, we have the Cost column in the table that links to @tkadlec 's awesome website for estimating the monetary costs of visiting a webpage. 
Idea: Add a column for "Carbon Cost", perhaps displaying the values as a letter grade or 
![image](https://user-images.githubusercontent.com/19509110/141370981-02eda648-0f28-4aa3-a264-08bba0653e5c.png)

**Comment by rposbo** [comment]
I think I consisted some of these points on  https://github.com/rposbo/greentree

It uses the Carbon Calculator logic for most info, but doesn't go into the fantastic details mentioned above.

This article has some brilliant details about trying to calculate this story of data too https://sustainablewebdesign.org/calculating-digital-emissions/

**Comment by rposbo** [comment]
WIP PR for the WPT Agent to include `greenhouse` plugin - https://github.com/WPO-Foundation/wptagent/pull/450

**Comment by shaneniebergall** [comment]
Great points by all above - here's what I see needs to happen:

1) Agree on list of metrics and where we get the data. We also have to decide whether this is computed on the WPT Agent or the WPT Server (pros and cons of each, as well as limitations on what data sources we use - example: greenhouse is an agent-only solution). Also need to be mindful of response times of these data sources (I saw that one of the APIs would time out under load - are these reliable enough for this?) Data sources to consider:

- [Website Carbon API ](https://gitlab.com/wholegrain/carbon-api-2-0)- recently migrated to cloudflare workers, but is missing readme at the moment so unable to determine all the data it provides
- [Green Web Foundation API](https://admin.thegreenwebfoundation.org/api-docs/) - the fundamental source
- [Greenhouse Lighthouse plugin](https://github.com/thegreenwebfoundation/lighthouse-plugin-greenhouse) - doesn't appear to have been updated in 2 years

2) Implement data collection and calculations

3) Expose results:
 - On the results page as a score
 - On a new detailed Sustainability tab which breaks down the results as well as provides thorough explanations
 - Through WPT's API

Thoughts?

Also, how do we ensure this will be adopted by master WPT? This is my first open source experience and I'd be bummed if we implemented this but it sat stagnant, unmerged.

**Comment by rposbo** [comment]
I'm thinking that we could pull in/directly reference the data sets used to power the GWF API, and ensure there's a circuit breaker pattern implemented: https://www.thegreenwebfoundation.org/green-web-datasets/

I believe the main model with WPT is to offload processing to the agent where possible, and only use the server where things *might* be needed later on, and it can't be known by a single agent (e.g., comparison videos)

I'm not sure where @tkadlec 's website cost is calculated, but that could be an appropriate model to copy?

**Comment by tkadlec** [comment]
:) Love all the excitement around this  one!

> I'm not sure where @tkadlec 's website cost is calculated, but that could be an appropriate model to copy?

That is computed after the fact, mostly independent of WebPageTest's agent and server. It looks at the data from a WebPageTest run and uses that to calculate the cost. In the WebPageTest results, where you see the dollar signs, Pat used a simple "for every 500kb, add a dollar sign" approach to hint at the cost, but the actual cost isn't actually known to WPT at all at the moment.

> Expose results:
> On the results page as a score
> On a new detailed Sustainability tab which breaks down the results as well as provides thorough explanations
> Through WPT's API

I definitely think this is something we want to bake in at some point (rather than rely on an external integration using the API).

We've got some stuff in the works that will come into play here, but for now I'm thinking both a general "score" for sustainability as well as a meaningful presentation of the data are both highly relevant and useful.

> I'm thinking that we could pull in/directly reference the data sets used to power the GWF API, and ensure there's a circuit breaker pattern implemented: https://www.thegreenwebfoundation.org/green-web-datasets/

Yeah, when we've talked about doing this this was the plan. I'd rather go straight to the source here and then see what kind of useful information we can get, whether we should pair it with anything, and how we should present it.

**Comment by rposbo** [comment]
> :) Love all the excitement around this one!

Not to pre-emptively overstate the potential benefits of this, but exposing the approximate environmental impact of a website to something as ubiquitous to website testing as WebPageTest could help to push this into the average business's conciousness, such that we start comparing ourselves to competitors not only by speed, but also by environmental impact. 

My hopes are that this could snowball into becoming a new ranking factor in search engines (any Googlers on this thread who can help? 😉), thereby forcing companies to become more aware and considerate about the 3rd parties, infrastructure, and application code they decide to use.

Help us, @tkadlec , you're our only hope 😁

**Comment by shaneniebergall** [comment]
I found the ['website cost' code](https://github.com/WPO-Foundation/webpagetest/blob/master/www/include/RunResultHtmlTable.php#L415) that @tkadlec and @rposbo were referring to, and now I understand what Tim was saying about it being more of a display element than an actual calculation. Doesn't seem like the model to follow here.

Sounds like everyone is leaning towards grabbing a copy of the GWF dataset and using that instead of relying on a third party. Was looking at the data yesterday and just wanted to point out that it's currently 200MB when uncompressed, and appears to be stored as "SQLite format 3". Is that usable within the WPT server setup? Last I checked WPT didn't use a database but instead just relied on the filesystem.

**Comment by shaneniebergall** [comment]
Apologies if I'm being too verbose here, just trying to document my thoughts along the way - 

I realized that the CDN check is very similar to what we're trying to achieve here, and that may be a better model to follow. It appears that detection is done at the agent level, using [an array here](https://github.com/WPO-Foundation/wptagent/blob/master/internal/optimization_checks.py#L63). If we mimic that approach, we'd need each agent to periodically download the large GWF dataset and then check against that - doesn't appear to be a problem, but is a lot of data, and this dataset is just going to keep getting bigger (hopefully). 

I'm wondering if it'd be better to have GWF expose the green hosts, instead of the urls, but am not sure how we'd determine the host of the url. I'll reach out to GWF to see how they do it.

@rposbo I see this [WIP](https://github.com/WPO-Foundation/wptagent/pull/450) and I think you have the right approach to implement this at the agent level, but sounds like we don't want to rely on 3rd party apis (greenhouse depends on the GWF API, yes?)

On another note, I'm used to implementing unit tests with every PR, yet I'm seeing some PR's in the wptagent repo that are passing checks but have parse errors in them ([example](https://github.com/WPO-Foundation/wptagent/pull/307/commits/6aa6aeabd0ab95074f695b01687b48185ca97d08)). @tkadlec Are the TravisCI build checks working as intended?

**Comment by mrchrisadams** [comment]
Hi folks - I'm one of the people working on the green web foundation databases and code, and I was tagged in a slack channel mentioning this issue.

We started releasing the sqlite snapshots with exactly with this use case like this in mind, so this was a nice issue to come across!

I've linked to an example below some code using it the local snapshot, in a plugin that powers searx, a search engine that uses here. It essentially treats sqlite like a key-value store:

https://github.com/searx/searx/pull/1878/files

A little more about that project below:
https://www.thegreenwebfoundation.org/news/searching-the-green-web-with-searx/

The examples there might help if you're looking to implement something local. Or come to think  of it, you could use it to demonstrate prototypes of factoring in greener infrastructure in search engine result ranking decisions (!).

### Keeping the snapshots small.

In the sitespeed plugin we used the sqlie snapshots too to begin with. It was eventually swapped out in favour of a big ol' json file, to avoid needing to compile a version of sqlite on npm install. 

You could plausibly do that too, but we've had some success with accessing compressed key value data too from various tools, that might be another approach later on once you have this working.

Internally, we use MariaDB for running the green web foundation database and we've started using the MyRocks storage engine to save space. This uses RocksDB under the hood, and more or less halves the size of the tables. If you want fast, local, in-process key-value access to the compressed data, that may be an option for you if you need to keep local size small. I think there are node libraries for using Rockdb, but that might introduce a compile step.

We've also started storing some data as Parquet files , and using DuckDB (another in-process database, like sqlite) to access the compressed files too. We haven't used this for the domain info yet, but it's given us pretty dramatic savings storage wise on other tables with lots of repetitive data. you can read a bit more about duckdb and parquet files here. It's been the most convenient way to access compressed parquet files we've found, and I think there libraries for using it from node too).

### CO2.js

We have a bit of work scheduled in December to implement that CO2 calculation model used by ecoping and website carbon that's outlined below here, and have it as an option, like we have with the one byte model from the shift project. 

https://sustainablewebdesign.org/calculating-digital-emissions/

This would help make numbers consistent across websitecarbon, sitespeed.io, ecoping, and presumably now webpagetest.

If you're looking at methodologies for calculating CO2 figures it might be worth being aware of this project too - it's a proposed spec to develop models against for calculating emissions from software:
https://github.com/Green-Software-Foundation/software_carbon_intensity

Anyway - while I'm out the rest of the day today, and I'm happy to share anything I know that would help 👍

**Comment by shaneniebergall** [comment]
Sounds like we're all in agreement about using the GWF data as our source here. Now we still need to decide the best approach to interact with that data. Here are the options I see (please do add others if you have them)

### Option 1: GWF Database on Agent

Each agent downloads, extracts, and serves locally via sqllite the GWF ['Green Urls' dataset](https://admin.thegreenwebfoundation.org/admin/green-urls).

Concern is that dataset is currently 200MB uncompressed (and has doubled in size since 9 months ago, so has potential to get quite large). But maybe this isn't a big concern since agents are typically run on better hardware than the server?

Also, the data is not going to change from one run to another (within the same test suite), so seems a little silly to have this computed with every run (ie, if our test comprises of 3 runs (the default), there's no point collecting this same data 2 extra times).

### Option 2: GWF Database on Server

While this goes against the typical WPT model of having the agents doing most of the work, it requires less storage overall (only 1 copy on the server as opposed to on every agent).

This solves the issue of unneeded extra calculations done at the agent level, and isn't dependent on any specific browser.

### Option 3: Greenhouse lighthouse plugin on Agent

The [Greenhouse plugin](https://github.com/thegreenwebfoundation/lighthouse-plugin-greenhouse) already utilizes the GWF API to check each domain. This solution probably requires the least amount of new code.

However, under the hood it relies on third party API, and the data returned is simplified to a score and a table. That'd make it hard to show this data in other places, such as the optimization checklist or on request details.

But the biggest drawback here is it would require the 'Capture Lighthouse' option to be selected - which is currently defaulted to Off - and would only work with Chrome agents.

### Option 4: GWF API on Agent/Server

Take Option 1 or 2 above, and use the [API](https://admin.thegreenwebfoundation.org/api-docs/) instead of the database. Less processing/storage needed, but introduces dependency on a third party.  Would also be unfortunate to hit the API at the agent level since green urls don't change within runs and we'd be hammering it harder than necessary.

Any other options I'm missing?

I feel like Option 2 offers the best balance, but would want buy-in from everyone involved since it doesn't follow the CDN check model.

**Comment by rposbo** [comment]
I agree with option 2, and I'd suggest that we use a simlar approach to that used for CrUX data; i.e., keep it on the WPT server (tho CrUX data is only cached for the URLs called, and deleted each day, whereas for GWF we'd keep it around and incrementally refresh) and **add to test result data (in the gzip results file) after test completion**.

WPT Server runs a test, requesting CrUX data for the URL:

https://github.com/WPO-Foundation/webpagetest/blob/0bf8d8e10fbfda646d74e9b60c49b882d8eaf200/www/runtest.php#L2300

WPT Server checks local cache first, 

https://github.com/WPO-Foundation/webpagetest/blob/0bf8d8e10fbfda646d74e9b60c49b882d8eaf200/www/include/CrUX.php#L36

failing back to API call:

https://github.com/WPO-Foundation/webpagetest/blob/0bf8d8e10fbfda646d74e9b60c49b882d8eaf200/www/include/CrUX.php#L4

Looks like the WPT server has an hourly cron to remove cached CrUX data that wasn't cached today:
https://github.com/WPO-Foundation/webpagetest/blob/4eed66053db2bdae8caf04904268ed8eb12347a9/www/cron/hourly.php#L28

Installing the GWF database on the server can be a WPT Server installation option, pulling down the latest GWF mysql backup (or other data source format if preferred), and adding a cron job to refesh weekly/monthly.

Makes sense to me 😄

**Comment by mrchrisadams** [comment]
Hey folks, this might be useful to know - you can pull down the snapshot there, but we also make this information in queryable form using [datasette](https://datasette.io/)

So you can fetch from this link:

https://admin.thegreenwebfoundation.org/admin/green-urls

But every morning a snapshot is made from MySQL, and put onto our datasets microsite using [datasette](https://datasette.io/). The idea here would be that people could make read-only, arbitrary queries in SQL that we hadn't written into an API yet, without unexpected load on the main database.

## API on datasette

This itself has an API, that lets you return the results of an SQL query in json or csv form.

So this query to get all the domains, orered by descending date order:
https://datasets.thegreenwebfoundation.org/daily_snapshot/greendomain?_sort_desc=modified

Is also available as json:
https://datasets.thegreenwebfoundation.org/daily_snapshot/greendomain.json?_sort_desc=modified

## Downloading just a section

If you know you're doing a daily download you can filter the query to only show the last 24 hours of updated domains rather than downloading the whole dataset each time. The example below where I filtered to only show domains which have an modified time of greater than `2021-11-27` returns 40-45k results, rather than 2.5m results

https://datasets.thegreenwebfoundation.org/daily_snapshot/greendomain?_sort_desc=modified&_sort_desc=modified&_sort_desc=modified&modified__gte=2021-11-27&_sort_desc=modified

You can also download these in JSON/ CSV form too:

https://datasets.thegreenwebfoundation.org/daily_snapshot/greendomain.json?_sort_desc=modified&_sort_desc=modified&_sort_desc=modified&modified__gte=2021-11-27&_sort_desc=modified

## Caveats and limitations

- The instance of datasette is reading off an sqlite snapshot, and I can't remember precisely when the daily cronjob runs, to make this snapshot of the main MySQL/Mariadb database. You might see differences in an API response compared to the snapshot for this reason - if the latest snapshot sqlite file hasn't been made yet and picked up by Datasette.

- Datasette has a [default timeout limit of 1000ms](https://docs.datasette.io/en/stable/settings.html#sql-time-limit-ms). I think i've extended the default timelimit to 3500ms, but some queries do still trigger timeouts.
- Datasette also [defaults to returning 100 rows in json/csv form](https://docs.datasette.io/en/stable/settings.html#max-returned-rows) - you can override this limit, and paginate through results, but I haven't really done too much testing on which queries trigger a timeout, or if this is more convenient than just downloading the snapshot itself. The datasets website doesn't get too much traffic, so i'm open to extending the query timeout in future if it makes cron-based updates easier.

**Comment by tkadlec** [comment]
Phew. Sorry for being tardy...had a long break and ya'll have been busy! :) LOVE all the excitement here.

> @tkadlec Are the TravisCI build checks working as intended?

@shaneniebergall Those are...no, not working. :( We've added some proper unit tests to the server now, but still need to dress up the agent a bit.

> I agree with option 2, and I'd suggest that we use a simlar approach to that used for CrUX data; i.e., keep it on the WPT server (tho CrUX data is only cached for the URLs called, and deleted each day, whereas for GWF we'd keep it around and incrementally refresh) and add to test result data (in the gzip results file) after test completion.

@rposbo Just curious: why would you prefer/suggest the DB here? The more I had looked, the more I thought an approach like CrUX (use an external API, but cache the results) would make a lot of sense here. Not really disagreeing, to be clear, just want to understand if there's a con to that approach that I'm overlooking.

**Comment by rposbo** [comment]
Thinking through this some more in order to explain my point, I've realised that you're correct @tkadlec ; using the exact same approach as CrUX (call API, cache response, prune cache) makes sense. 

Make it so! 😁

**Comment by rposbo** [comment]
Just to add a teensy bit more oomph to this request - even AWS have introduced a Sustainability Pillar in their Well Architected framework... and we wouldn't want WPT to fall behind, would we? 😁 

https://aws.amazon.com/blogs/aws/sustainability-pillar-well-architected-framework/

**Comment by shaneniebergall** [comment]
Great insights - the CrUX model looks like a wonderful approach to model after. Looks like in order to keep things manageable, the CrUX integration was done in multiple phases, with the [first phase to collect the data](https://github.com/WPO-Foundation/webpagetest/commit/3b8506c7bea65ed8f7caa6b3914ac34c1bb31274), followed by [another phase to add the data to the UI](https://github.com/WPO-Foundation/webpagetest/commit/4ed3104ebbdba87c4065813c2ea5569e94ef91b9). Shall we do something similar?

One way we will differ from the CrUX approach is the cache. CrUX results are cached for the day, with each url as en entry in the day's cache folder. Yet we'll want green domains to be cached longer than that, right? (How often do sites change hosts?) Perhaps this is something we store monthly? (and if so, is it going to be problematic that there will be a large influx of API requests to the GWF at the start of the month?). Also curious if we'll run into directory limitations if we have a file per domain - might we need to shard this like other results?

Last thought, if we're really trying to encourage a green web I'd love for this to be included in the apache branch too. That would give other providers (catchpoint competitors) the ability to promote sustainability as well. How do we plan for that?

**Comment by shaneniebergall** [comment]
I'd love to put some time into this over the holidays...but want to make sure I have a solid plan. Any input on my last couple questions? @tkadlec

**Comment by paulirish** [comment]
FWIW we have a very similar thread over in the Lighthouse repo: https://github.com/GoogleChrome/lighthouse/issues/12548

**Comment by fershad** [comment]
Just a note that the MS Edge team has a proposal out to surface some sustainability & energy usage data in Chrome DevTools. https://github.com/MicrosoftEdge/DevTools/blob/main/explainers/Sustainability/explainer.md

**Comment by rposbo** [comment]
Checking in a year on from this discussion being kicked off - is there anything we can develop (on the apache branch too) to help expose this info in WPT, or are we waiting on edge and chrome/lighthouse to implement some standard?

**Comment by shaneniebergall** [comment]
> Checking in a year on from this discussion being kicked off

@rposbo I was excited to work on this until I read the [thread that Paul pointed us to](https://github.com/GoogleChrome/lighthouse/issues/12548), which said "The scientific community has not yet reached a consensus on how specifically to measure emissions from any digital product or service. And I'm not expecting this to happen anytime soon." as well as "I've looked at the various efforts to quantify website energy use/carbon footprint but currently they're rather under-developed compared to web performance or accessibility testing. They primarily use proxy metrics like network request count or byteweight. But relying on these is far too indirect."

Others seemed to agree, and the Lighthouse issue was closed with no work. 

That took the wind out of my sails...Unless we hear from those that have the power to merge within WPT, I'd hate to work on a lost cause.

**Comment by scottjehl** [comment]
HEY EVERYONE! We've closed this issue because the Carbon Control feature (centered around a carbon footprint metric) has landed in WebPageTest!

Thank you to everyone here who commented and shared ideas and shared this post and +1'd it. It helped us keep the feature prioritized and heavily shaped the direction of the first release.

Here's a blog post about Carbon Control and how you can use it now in WebPageTest: https://blog.webpagetest.org/posts/carbon-control/ 

And you can try it out on the homepage, or here:
https://www.webpagetest.org/carbon-control/

TY! @tkadlec @Nooshu @fershad @paulirish @rposbo @mrchrisadams @shaneniebergall @screenspan

**Comment by shaneniebergall** [comment]
Thank you @scottjehl and all who worked on this. I'm thrilled it is released and can't wait until it becomes the default. As developers we seem to think the environment is only impacted by air travel, cars, corporations, etc. This enables us to become aware and make a difference in the world. YOU ROCK!

**Comment by scottjehl** [comment]
@tbroyer thanks for your feedback (I replied to your post on another platform just now too). Our teams have been evaluating the work around this for a year or so now and went into the space with an ample amount of curiosity and reservations. The actions the tool recommends, like identifying green and non-green hosts and reducing wire weight, are frequently cited as great actions to take towards a more energy efficient presence on the web. They're frequently requested from folks who are increasibingly being asked to measure and be accountable for their digital footprint as well (eg https://www.gov.uk/government/publications/greening-government-ict-and-digital-services-strategy-2020-2025/greening-government-ict-and-digital-services-strategy-2020-2025#supply ) The changes this tool recommends are certainly not exclusive of other actions you can also take (many of which may be much more impactful too, if often out of developers hands), such as advocating for reducing device turnover as your article helpfully recommends. 

To your point on the CO2 model, we're using the Sustainable Web Design model, not 1-Byte.

**Comment by mgifford** [comment]
@tbroyer I do think we need to jumpstart the conversation about this issue. It's not new, but in our industry do not have an understanding of the impact of the digital world on our physical environment. It's important to critique the use of tools like CO2.js, so that they can get better. 

There are lots of reasons to be wary of any scoring system. Goodhart's law is a real phenomeno (When a measure becomes a target, it ceases to be a good measure). However, we also need to find some means to materialize in some way what is a very complex series of variables. 

Your article has some great points in it https://blog.ltgt.net/climate-friendly-software/ but shaping an industry such that peoples devices have a longer life-span is a real challenge. So much of that will come down to their user expereince. Much of that will be based on how quickly, and reliably users are able to engage with the sites that they want. 

That kinda brings us back to Google Lighthouse scores and efforts to highlight to developers with fast machines and broadband that their experience isn't the same as their users.
