### ISSUE TITLE
webpagetest site: apply fonts to elements in the page to kick off custom font requests sooner

### ISSUE THREAD

**Issue by scottjehl** [WPO-Foundation/webpagetest#2167]
These font-face rules are in a good place, but the fonts aren't requested until rules defined in pagestyle2.css apply the fonts to the page and kick off their requests. We should add a rule or two to handle that sooner at the end of the inline style block here.

<img width="744" alt="image" src="https://user-images.githubusercontent.com/214783/179531528-23206024-2bb1-42eb-95e4-9d9614095f0e.png">

**Comment by tkadlec** [comment]
Hmm....don't think that's going to make a big difference? Fonts won't be requested until the page knows what will be displayed, which requires all blocking CSS to be downloaded and parsed, and the CSSOM and render tree to be created.

Since the external CSS loads in a blocking manner, that means fonts won't get kicked off until it's downloaded anyway.

**Comment by stoyan** [comment]
How about `<link rel="preload"`? or HTTP header?

**Comment by stoyan** [comment]
Also maybe keep only WOFF2? https://caniuse.com/woff2 vs https://caniuse.com/woff is just IE

**Comment by scottjehl** [comment]
closing as low-pri
