### ISSUE TITLE
Feedback on new Lighthouse report

### ISSUE THREAD

**Issue by connorjclark** [WPO-Foundation/webpagetest#2587]
Hey, I work on Lighthouse and just saw your recent [announcement](https://blog.webpagetest.org/posts/webpagetest-lighthouse-even-better/). I shared some thoughts on it with coworkers and thought y'all might benefit from them too. Hope it helps!

First of all, really love it, I think it looks great!

_____
(copy/pasting here!)

Some interesting things I'm noticing in comparison with Lighthouse's renderer (WPT uses a custom one; perhaps by calling our code and tweaking some things, unclear):

WPT report renderer: https://www.webpagetest.org/lighthouse.php?test=221214_BiDcSF_CRE&run=1
Lighthouse report renderer: https://googlechrome.github.io/lighthouse/viewer/?gist=99c82f9003892a8b508df0632c14335c

- As they've always done, they exclude the full page screenshot so some audits have far less context in theirs (example: LCP element diagnostic audit is just a selector; all the a11y audits). They do this for storage concerns, I suspect.
- Tables are scrollable horizontally. We don't need to do that, because we elide the URL and present it differently to control for the width, while they show the full URL; we also have had many battles with word-wrap they they get to ignore with this approach
- We have some audits we decide to hide 3p by default, they don't seem to know about that and will show everything that may be un-actionable (ex: the legacy javascript audit). We have a 3p filter toggle but they just show all the results in every audit.
- We show bytes abbreviated with KiB, but they show raw bytes in the table
- They make much better usage of the final screenshot in the report
- **Their top-line description of category score will actively mislead users that Performance category audits impact score directly ("Category scores summarize their contained audits")**
- Their audit icons are awesome
- They don't render our various markdown text as monospace font w/ a background to denote its code
- For some reason their metric audit filter reloads the page
- I appreciate the inclusion of the treemap :)
- I suspect they do not render any of our table details subItems, which is a big loss for audits like "unused javascript", etc. which will utilize source maps when available. We are also starting to utilize this feature much more, so there may be audits that just make no sense when ignoring subItems

(I bolded the one item I think is most important to address–we are constantly battling the perception that the Lighthouse score is calculated from audit opportunities)

_____

I tried to run an audit a site I know has source maps, but I got an error: https://www.webpagetest.org/lighthouse.php?test=221214_AiDcWM_GYZ&run=1 `Sorry! That page doesn't appear to exist. If you think you have the right link, perhaps try logging in to see if anything changes.`

**Comment by scottjehl** [comment]
@connorjclark It is so great to have your feedback on this! Thank you so much for taking the time!

First, so happy to hear you like it. It was fun to work with the JSON and learn more about Lighthouse in the process, and we were particularly happy to start making some associations to our Experiments from LH's audits, but there's definitely more work to do there.

As for the rendering process ("unclear"), we're [consuming the JSON output directly in PHP](https://github.com/WPO-Foundation/webpagetest/blob/master/www/lighthouse-new.php), and templating it out in blade/php. There's very little clientside JS involved.

Every note here makes a great point that will be useful as we refine our first release. At a glance, many of the shortcomings or differences in audit density are not intentional decisions, but likely more of an area where we need to revise how we're parsing some of the details objects. We found it a little challenging to discern some of the differences in json structure for the details between different kinds of audits, and I think we just need to improve on that for some types.

For your bold bullet point, we'll definitely want to address that first. We'd like to have retain some sort of quick sentence that describes the color coding of the scores at the top, but maybe we could omit that part and simply have the color key. It sounds like at least for the Performance category, the score is calculated from metrics rather than audits, but I'm unclear on the wording for the other categories. Open to suggestions if you have one.
Issue filed: https://github.com/WPO-Foundation/webpagetest/issues/2589

You found a couple of genuine bugs as well, thanks. Looks like our sorting by metric only works on tests that include LH as part of a broader WPT test (like this one), so we'll fix that query string logic up for standalone lighthouse tests today.
Issue filed: https://github.com/WPO-Foundation/webpagetest/issues/2588

We'll file more issues 

Thanks again!

**Comment by scottjehl** [comment]
Hi again @connorjclark 

We've filed issues and as a result of this issue, and most of them are closed already as well - thank you again for that!

I think the rest of the points note some differences in our approach.

Thanks so much again!
Scott

**Comment by connorjclark** [comment]
Thanks Scott, and happy new year! 🎉
