### ISSUE TITLE
Line endings in the project

### ISSUE THREAD

**Issue by sergeychernyshev** [WPO-Foundation/webpagetest#292]
What's the right way to escape line endings in the project?

I seem to be getting issues with Git complaining about line endings on my modifications (I'm on a Mac).

**Comment by sburnicki** [comment]
I'd like to revive this issue since I want to get involved and I'm primarily using linux.
It seems like CRLF is used in most files. Mostly it's recommended to use only LF in the repo and convert at checkout/checkin on Windows as suggested [in the documentation](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace).
We can also configure this with a [.gitattributes](https://git-scm.com/docs/gitattributes) file for the repo.

However, converting all the files would result in quite ugly commits, I guess.
Though forcing CRLF seems not to be the standard way, it should also be possible with the `.gitattributes` file.

So what is the desired behavior: Switching to LF as recommended, or try to force CRLF.
Either way, I would like to add a .gitattributes file to the project so the behavior is defined.
Any comments @pmeenan ?

**Comment by sburnicki** [comment]
Okay, I need to correct myself: It does not seem to be possible to force CRLF on commit, only on checkout. Which is cool for windows if the files have LF in the repo, but they don't.

So the alternative to using LF in the repo would be to pay attention in new commits that the line endings are consistent with the project (CRLF) and developers need to pay attention that the editor handles the line ending correctly.

For people having trouble with warnings and complaining git: Check out the `autocrlf` git setting.

**Comment by pmeenan** [comment]
I'd love to just transition all of the files to only LF and if we use a gitattributes, have it checkout and in as-is.

That kind of change is likely to be fairly disruptive to any fork or anyone working on a change though.  Maybe a policy of converting everything to LF if you touch it?

**Comment by sergeychernyshev** [comment]
At some point you need to make a leap like that - doing this one by one doesn't work as it is hard to do once already and doesn't help anyway.

Maybe bundle with some other cosmetic changes and release under next another minor version and just notify developers that they will have to port accordingly. Maybe do a grace period of a month and let them submit pull requests and brace themselves and deal with the merge if they miss it.
