### ISSUE TITLE
wptdriver for Chrome seems to send IE UA?

### ISSUE THREAD

**Issue by pganti** [WPO-Foundation/webpagetest#393]
1. Consider the test at http://www.webpagetest.org/result/150129_8S_EZ4/1/details/ where one might think it did run from a Chrome Browser
2. Inspect the request headers and you would see the following:

X-Download-Initiator: script="doc 0EA8 win B558; script element; src; property change"
User-Agent: Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko PTST/199

3. export the har and you can see "browser":{"name":"Internet Explorer","version":"11.0.9600.17496"}, is the browser

 What am I missing here?

**Comment by pmeenan** [comment]
Wow, I'm not often surprised but that did it.

wptdriver had a facility for a "default" browser if the server didn't specify which one to use with a test and it looks like that machine was configured with IE 11 as the default.  The support for a default is legacy from when the server didn't always specify which browser to use (which it has since 2.15) si I just [nuked](https://github.com/WPO-Foundation/webpagetest/commit/abeb2e9e595136d0c6ce38008701277754448265) the fallback code.

That said, since the server always specifies the browser and I didn't see anything specifically wrong with the test you ran it should have never triggered.  Now at least it will error out in that condition instead of running the wrong browser which will hopefully also make it easier to spot.

I re-ran the same test across all of the chrome agents and verified the UA strings and they look correct now.  Let me know if you see anything strange again (or failures with launching browsers).

**Comment by pmeenan** [comment]
Fixed (a while back). The support for "default" browsers was removed
