### ISSUE TITLE
Possible to wire up a newer iOS device/version for testing?

### ISSUE THREAD

**Issue by scottjehl** [WPO-Foundation/webpagetest#404]
The only iOS option on WPT is version 5, 3 versions behind the current. It'd be really great to be able to test on iOS amongst other 3G mobile devices, particularly since iOS has a bunch of quirks with regards to how it loads web fonts (long hidden text timeouts, etc)

Thanks!

**Comment by pmeenan** [comment]
iOS is in a kind of complicated state with a few options.

#Mobitest agent
This is the current iOS agent.  It was the best that could be done at the time but it hasn't been updated in a while and there are some serious drawbacks:
* Video capture impacts test performance (upwards of 30%) and can only be done at a very low frame rate (1 fps on the public agents)
* The request data does not include socket connection and DNS times
* Relies on UIWebView which doesn't perform as well as wkWebView which is the new way for embedding in iOS 8
* Doesn't work with iOS 7+ (needs some tweaks to the API hooks)

#Node JS agent
This is the main agent we use for Android testing and can also drive Safari on iOS (the full browser)
* Relies on the [ios-webkit-debug-proxy](https://github.com/google/ios-webkit-debug-proxy) which may need to be updated to support iOS 8 (discussion list has mixed success)
* The request data does not include socket connection and DNS times
* Requires a jailbreak so the browser cache can be cleared
* No good solution for video capture (it can use HDMI-based capture devices but that doesn't work for most devices and is seriously complicated)

We could update the mobitest agent code but the video capture problem and limited waterfall data don't make that very appealing.

I could probably add newer devices with the node agent but they wouldn't have video capture support which pretty much defeats the purpose of what you are looking for.

The video capture support is the biggest problem and one I've been experimenting with as I get time.

iOS 8 added support for capturing device video over lightning from Quicktime but they didn't add it as a video source that anyone can use (at least in the testing that I did).  My current plan is to reverse-engineer the video capture protocol and talk to it directly like we do with the debug proxy but that's a pretty steep curve.

The other thing I've been considering is to take a look at [RecordMyScreen](https://github.com/coolstar/RecordMyScreen) and see if I can update the code to work with iOS 8 and get on-device video capture working for both mobitest and the new agent.  I took a quick stab at it but it's going to be somewhat more involved and I'll have to find serious time to look into it.

I'm leaning towards the native OS X lightning capture since it's actually supported by Apple for mostly this purpose.

Once video capture is solved I should be able to deploy some newer devices with iOS 8 testing actual Safari.  The network data will still be a bit iffy but we can use tcpdumps to augment the request data we get from Safari.

**Comment by pmeenan** [comment]
oooh, some progress.  Apparently there is a secret handshake you need to do with Apple's API's to get it to show iOS devices in the capture device list.  There's another issue right now where the device only shows up if quicktime is running but I filed a ticket with them to see if I'm missing something simple.

With any luck I'll have a command-line utility ready in the next few days that can do the screen recording of iOS 8 devices and hopefully get something set up in the next few weeks (I'm out of town next week so it might get delayed a bit).

**Comment by pmeenan** [comment]
[command-line video capture](https://github.com/WPO-Foundation/xrecord) is now a thing (as of yesterday).  Just a couple of edge issues to sort out but it's basically ready to go.

Next step is to integrate it with the Node agent (should be trivial) and make sure all of the node agent plumbing for iOS still works (that's a bigger deal - I think there may be ios proxy work to work with iOS 8).

**Comment by cwmanning** [comment]
+1 would love to test iOS 8 on newer devices

**Comment by scottjehl** [comment]
Hey @pmeenan - just wondering if there's been any good news on this from the iOS side? Would still love to see it!

**Comment by pmeenan** [comment]
Not yet.  I keep getting distracted by less daunting issues.

It looks like there has been a lot of progress with the debug proxy so I am going to make another run at it (just bought and jailbroke an iOS 8.4 5C for dev testing).  I have some work to do on Chrome proper (not WPT related) but will hopefully be able to get back onto it after that.

**Comment by pmeenan** [comment]
Still shaking out some of the cobwebs and figuring out the scaling but iOS 8 is now up and running on an iPhone 5C on the public instance.
