### ISSUE TITLE
Location ID's have an inconsistent syntax

### ISSUE THREAD

**Issue by okor** [WPO-Foundation/webpagetest#428]
Using the wpt node driver, a request to .getLocations() returns a JSON object listing locations. But the naming scheme for ID's for IE test agents is not consistent with other browser types. See this gist https://gist.github.com/okor/e519382c52d4921e770e

For example:
```
"location":
  [  
    {  
       "id":"us-east-1:Chrome",
       "Label":"US East (N. Virginia)",
       "location":"us-east-1",
       "Browser":"Chrome",
       "labelShort":"US East (N. Virginia) - Chrome",
       ....
    },
    {  
       "id":"us-east-1_IE11",
       "Label":"US East (N. Virginia)",
       "location":"us-east-1_IE11",
       "Browser":"IE 11",
       "labelShort":"US East (N. Virginia)",
       ...
       }
    }
  ]
```

The separator flips from a colon to an underscore. This makes it more difficult to automate tests where you'd like to define a fixed location to perform a test.

I assume this is the result of the server and not the API, though I suppose it could be munging keys ... seems unlikely.

**Comment by pmeenan** [comment]
That's a function of how things are configured and isn't going to be easy to change.  The colon separator is used to specify a browser from a location that supports multiple browsers and technically the IE 11 location could be referred to as "us-east-1_IE11:IE 11".

Each of the EC2 locations is configured to pull from 2 different locations because Chrome and Firefox can run on all of them regardless of what version of IE is installed so if you have an IE 11 and an IE 9 VM running then both of them can run Chrome or Firefox tests.

That said, if you are only using IE 11 VM's then you can submit tests to "us-east-1:IE 11" and it should work.  If you have any IE 9 (or 10) VM's in the mix then there's a chance it will fail if one of them picks up the job.

**Comment by okor** [comment]
Perhaps the better option would be to separate the two values in the API? Something like this:

```
wpt.runTest("http://www.theverge.com", { 
    pollResults: 10, 
    timeout: 60,
    zone: 'us-east-1',
    browser: 'IE11'
  }, function(err, response) {
  console.log( JSON.stringify(err || response) );
})
```

That could also be backwards compatible. Assuming WPT maintains an internal mapping.


We currently use all browsers available on a private instance, fyi.

**Comment by pmeenan** [comment]
That wouldn't really work.  We'd still have to maintain a mapping somewhere for what zones and locations supported which browsers (at least with how everything is managed internally to WPT).  It doesn't technically know about zones, just more generically "locations" that support a list of browsers.

The only reason it gets complicated is that we didn't want to waste capacity and only be able to test Chrome with one AMI like we have with IE so the EC2 instances overlay 2 sets of locations to make it work.

Longer term we might be able to have the agents advertise which browsers are configured and only pull work for supported browsers which would eliminate the issue but it would significantly complicate the work queues.

**Comment by okor** [comment]
Hmm, right. That is tricky. Welp, I'll close this ... but would love to have it someday. "Nice to have"

Thanks for all your hard work. And the new AMI is pretty fantastic.
