### ISSUE TITLE
Question: Scripting command deliminator

### ISSUE THREAD

**Issue by EliSnow** [WPO-Foundation/webpagetest#472]
In the [scripting documentation](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting) I don't see any mention of delimiters for the commands. Specifically I'm wondering how far I can push the `exec` command. Can I have Javascript which spans multiple lines? If not, can an arbitrary amount of Javascript be minified to be on one line and run with the `exec` command?

**Comment by pmeenan** [comment]
Each command needs to fit on a single line and tab characters are used for delimiters so as long as all newline and tab characters are removed you should be able to use arbitrary-length exec commands (within reasonable limits of arbitrary - no more than 100MB for sure since the post limit is configured to that).

**Comment by pmeenan** [comment]
btw, the delimiter is referenced in the 3rd paragraph of the scripting documentation.
