### ISSUE TITLE
"Include call stack" chrome option doesn't work

### ISSUE THREAD

**Issue by tusheto** [WPO-Foundation/webpagetest#506]
Hi,

I can't see difference between two measures with call stack on and off. There are no flame chart even when the option is on. 

Best regards,
Todor

**Comment by pskelin** [comment]
Here is a test with timeline recording and include callstack option turned on.
http://www.webpagetest.org/result/151015_C1_KQW/

The recorded timeline doesn't have the callstacks recorded:
http://static.webpagetest.org/chrome/inspector-20150519/inspector.html?loadTimelineFromURL=/getTimeline.php?test=151015_C1_KQW&run=1&cached=0

What is even stranger is, that the whole test run fails for some sites when timeline with stacktrace is on (like the google homepage here):
http://www.webpagetest.org/result/151015_3T_KP9/

**Comment by pmeenan** [comment]
Flame charts should show up correctly now (the embedded timeline viewer that WPT was using was from May and there have been quite a few changes since).

As far as tests failing, I'm surprised to see it happen with the Google homepage but the timeline/trace files are collected with a setting that tells Chrome to collect as much as possible regardless of memory limits (otherwise the timelines are truncated because the trace files can get to be REALLY big).  Sometimes that can cause Chrome to crash though, particularly on mobile devices and then you end up with no data.  I'll check to make sure there aren't any opportunities for saving memory as the traces are moved around but you should expect failures from time to time when collecting stack traces (or chrome traces).

**Comment by pmeenan** [comment]
I just pushed an update that also reduces the amount of data being collected when capturing stack traces (no longer also captures a v8 profile) so it should fail a lot less frequently: http://www.webpagetest.org/result/151105_H6_T6F/

**Comment by justinthec** [comment]
Hi @pmeenan,
I think that the bug has returned, as I expect the Flame chart to include the call stack like this:
![image](https://cloud.githubusercontent.com/assets/2578036/17007251/1cb3a4e0-4eb5-11e6-8ecd-d7e2811dc732.png)

However when I turn on the `Include call stack` option, it only gives `Function Call` events in the timeline.
![image](https://cloud.githubusercontent.com/assets/2578036/17007220/df6ede42-4eb4-11e6-8d9b-4cdab5bb70c1.png)

**Comment by pmeenan** [comment]
@justinthec I took a look and also reached out to the dev tools team and the really deep flame charts you see in dev tools come from another capture method (running the profiler).  I'm looking into what it would take to add that as a data source as well but it's not quite the same.

**Comment by justinthec** [comment]
Ahhh awesome, thanks for the clarification. Is there a way to get that JS frame data in to timeline files?

**Comment by pmeenan** [comment]
Possibly.  I took a crack at it on Friday but I wasn't able to get the profiling events so my magic incantation wasn't quite right.
