### ISSUE TITLE
TTFB and Fully Loaded seems wrong for Firefox & SPDY

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#520]
Hi Pat,
I think there's been a fix for fetching TTFB for SPDY using Firefox? Before it was always 0 but now it seems to be too high. It looks like this on our instance (https://grafana.wikimedia.org/dashboard/db/webpagetest):
<img width="807" alt="screen shot 2015-11-05 at 8 58 34 am" src="https://cloud.githubusercontent.com/assets/540757/10962908/302a68ae-839c-11e5-8fe8-9dd41053b355.png">

It seems it also affect fully loaded. Tested on WPT.org and it looks like this:
<img width="941" alt="screen shot 2015-11-05 at 9 06 44 am" src="https://cloud.githubusercontent.com/assets/540757/10962965/9b22c91c-839c-11e5-83d4-8fe05bc3c625.png">

http://www.webpagetest.org/result/151105_JQ_DNP/4/details/

If I can choose I prefer if it reports 0 as before :)

Best
Peter

**Comment by pmeenan** [comment]
Looks like the new Firefox 42 release (and the privacy mode content blocking it added) is downloading some content in the background which tickled the ttfb since your site is spdy which isn't decoded by wpt.

I'll see what prefs are needed to disable the background downloads and should have it fixed today.  Thanks for the details.

**Comment by pmeenan** [comment]
All fixed: http://www.webpagetest.org/result/151105_4J_T3Q/

I also disabled the reader mode notification that started showing up with 42.
