### ISSUE TITLE
webpagetest agent run error on windows

### ISSUE THREAD

**Issue by sqflotus** [WPO-Foundation/webpagetest#524]
![image](https://cloud.githubusercontent.com/assets/10216116/11031442/7d9893a6-870f-11e5-80e7-5708b4142ecb.png)

Command :."/ipfw_config clear -- device *****", run failed on windows.

But in documents, agent can support windows platform.
https://sites.google.com/a/webpagetest.org/docs/private-instances/node-js-agent/setup

**Comment by pmeenan** [comment]
Does the location on the server have a fixed connectivity profile (connectivity=Something in locations.ini)?  To be able to do traffic shaping you need to supply a command-line to use to configure a remote bridge to shape the connection for the device, otherwise it will fail.  You should get it working without dynamic traffic shaping first.

It does support Windows.  That's what the host controlling the instances on the public webpagetest.org instance runs.
