### ISSUE TITLE
Node Agent : Mobile Android, webdriver script

### ISSUE THREAD

**Issue by darraghgrace** [WPO-Foundation/webpagetest#529]
Hi, 

I have a private WPT instance and node js agent running the latest from master. I have a rooted Samsung S5 hooked up and running tests with good results.
I want to run some webdriver scripts as part of this testing. I can run the following script from the documentation
driver = new webdriver.Builder().build();
driver.get('http://www.google.com');
driver.findElement(webdriver.By.name('q')).sendKeys('webdriver');
driver.findElement(webdriver.By.name('btnG')).click();
driver.wait(function() {
return driver.getTitle();
})
I can see the test running perfectly on my device, however I do not get any results back in WPT UI.

![screen shot 2015-11-15 at 14 49 20](https://cloud.githubusercontent.com/assets/2386816/11169176/230f0a76-8ba8-11e5-94a5-8d8ba26a0f95.png)

I have tried using logData 1 at the end of the script but still no results. Maybe I am missing a step? This functionality is great!

I am also using the latest chromedriver 2.20.

**Comment by klepikov** [comment]
I haven't looked at that code in a looong time, but here is my top suspicion... When the test has a WD script, the agent gets the DevTools trace from the browser via the WD Logging API, while for "regular" page load tests with just a URL, the agent connects to DevTools and collects the DevTools trace directly. So something may have rotted in one of the following:

1. Getting the DevTools trace via the WD Logging API.
2. Storing the trace correctly in the test results – the filename that the server expects etc.
3. DevTools Timeline is deprecated and replaced with the Tracing category Timeline. The WD Logging API does have Tracing support, but it very well be that the agent doesn't use it and still tries to enable and collect the old Timeline DevTools domain. That's not the most plausible theory though, because Timeline is optional, at least used to be optional – WPT UI would show the test results even without the Timeline being collected, it could show the waterfall based on the Network + Page events only, which the latest Chrome still generates fine.

I guess it might help to run the agent with most verbose logging and attach the agent log to this bug.

**Comment by darraghgrace** [comment]
hi, requested logs attached.
[webdriverlog.txt](https://github.com/WPO-Foundation/webpagetest/files/41714/webdriverlog.txt)

**Comment by klepikov** [comment]
Pat, bouncing this to you. I tried to repro here and get a results zip, but our devices are offline ATM, and I wouldn't be able to download a results.zip from the public WPT AFAIK. Again my suspicion is it may have broken because of an expectations mismatch between what WD returns in the performance log nowadays vs. what the WPT server wants.

**Comment by darraghgrace** [comment]
Hi @klepikov . Let me know if I can help. I can get you a zip file of the results folder in WPT server if thats any use to you?

Thanks

**Comment by klepikov** [comment]
Sure that might help, thanks.

Michael

Sent from my mobile device

**Comment by darraghgrace** [comment]
I've zipped up the results folder from WPT server and shared it here - https://drive.google.com/file/d/0BySxV3nfNRmtbFQzR21FOVdBZWc/view?usp=sharing

If there is anything else you need let me know.

Thanks

**Comment by klepikov** [comment]
The 1_devtools.json and 1_trace.json contain empty arrays, meaning the
performance log was empty. I'm afraid someone would need to live-repro it
and debug what's actually going on.

A chromedriver.log would also help – it would show the actual JSON-HTTP
requests that chromedriver received, the responses to those, and some
detail of the DevTools interaction with Chrome.

What version of Chrome is running on the phone? Chromedriver 2.20 release
notes say that it supports Chrome 43-48.

On the chromedriver side, the interesting code is between

https://chromium.googlesource.com/chromium/src/+/master/chrome/test/chromedriver/capabilities.cc

where it parses the desired caps and decides what DevTools event domains
and trace categories to enable in Chrome,

https://chromium.googlesource.com/chromium/src/+/master/chrome/test/chromedriver/performance_logger.cc

where it does the DevTools interaction related to these domains and events,
and

https://chromium.googlesource.com/chromium/src/+/master/chrome/test/chromedriver/session_commands.cc

in ExecuteGetLogs that handles the /log JSON-HTTP request.

**Comment by darraghgrace** [comment]
The chromedriver version is 2.20 and the version of Chrome on the device is 46.0.2490.76

I'll try get the chromedriver.log this afternoon
