### ISSUE TITLE
Question: Workflow for spinning up new agent instance on AWS

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#542]
Hi Pat,
we have an agent constant up and running on AWS configured for auto updates so we have the latest Chrome/Firefox and WPT code. 

When test changes we start an agent instance at another location, do a couple runs and then stop and remove it by the awesome built in functionality.

Been reading the original [issue](https://github.com/WPO-Foundation/webpagetest/issues/310) as I understand a new agent should first fetch the latest code and install the latest version of the browsers, before it's used or? When I test it seems like I sometimes (but not always) gets an old version of Chrome.  But haven't beed able to pinpoint exactly how it works. Or do the auto update happen only in the hourly cron?

Best
Peter

**Comment by pmeenan** [comment]
Are you using the public AMIs directly or did you make clones?

The AMIs should not have Chrome installed and it should be downloading and installing on first launch (from the URL in wptdriver.ini which usually points to the public instance browser list).  wptdriver won't poll for work until it has successfully downloaded and installed the browser.

If you launched an AMI and then cloned it the browser install will be stuck with whatever was installed when it was first launched and will rely on Chrome's built-in auto updating.

If it's a public AMI, let me know which one because it may be misconfigured if that is happening.

They will also pull the latest wptdriver from your WPT web server but I'm assuming that's not the issue.

**Comment by soulgalore** [comment]
Cool, we use the public AMI, let me check again and see if it happens, the last days haven't been able to reproduce the problem, I wonder if I somehow can have seen wrong? hmm. I'll update/close the issue in a couple days when I have checked more. Thanks again!
