### ISSUE TITLE
Default location selection bug in www/runtest.php

### ISSUE THREAD

**Issue by rmarx** [WPO-Foundation/webpagetest#552]
Hello Patrick,

I may have found a small bug in www/runtest.php for **private instances** in release 2.18:

When running "visual comparison" via web interface:
- This calls www/docompare.php, which then fetches runtest.php URL
- In www/runtest.php the error message "Invalid Location, please try submitting your test request again." is triggered in the ValidateParameters method
- This is because the `$test['location']` var is NULL at this point

If I var_dump( $locations ) in ValidateParameters, I get:

```
["locations"]=>
  array(2) {
    [1]=>
    string(3) "EDM"
    ["default"]=>
    string(4) "EDM1"
  }
```

But the original code to fetch the default location from this (since visual compare doesn't pass a location) doesn't seem to account for this setup:

```
if (!strlen($test['location'])) {
    $def = $locations['locations']['default'];
    if (!$def)
        $def = $locations['locations']['1'];
    $loc = $locations[$def]['default'];  // <-- here, $locations[$def] is already a string, not an object
    if (!$loc)
        $loc = $locations[$def]['1'];
    $test['location'] = $loc;
}
```

I've tested a quick-and-dirty fix which seems to solve the problem:

```
if (!strlen($test['location'])) {
    $def = $locations['locations']['default'];

    if (!$def)
        $def = $locations['locations']['1'];

    if (gettype($def) != "string") {
        $loc = $locations[$def]['default'];
        if (!$loc)
            $loc = $locations[$def]['1'];
    } else
        $loc = $def;

    $test['location'] = $loc;
}
```

I'm not sure why this problem shows up here, since it seems the code is not that recent...
Did something recently change in how you pass the $locations parameter?
Or is my locations.ini file weirdly built? 

My locations.ini for reference:

```
[locations]
1=EDM
default=EDM1

[EDM]
1=EDM1
label=EDM Agent 1
group=EDM

[EDM1]
browser=chrome,firefox,IE 11
label=All browses - Agent 1
connectivity=Native

```

**Comment by pmeenan** [comment]
default in [locations] should point to EDM, not EDM1

**Comment by rmarx** [comment]
I tried changing locations.ini to:
```
[locations]
1=EDM
default=EDM
```
But the error still persists. var_dump($locations) prints:
```
  ["locations"]=>
  array(2) {
    [1]=>
    string(3) "EDM"
    ["default"]=>
    string(3) "EDM"
  }
```

**Comment by pmeenan** [comment]
Do tests work through the normal UI (before working through issues with the visual comparison)?  The only thing that comes to mind is that locations will be removed from the list if test agents are not connecting.  Otherwise the var_dump should have a lot more in it.

The full locations.ini should look like this:
```
[locations]
1=EDM
default=EDM

[EDM]
1=EDM1
label="EDM Agent 1"

[EDM1]
browser=chrome,firefox,IE 11
label="EDM Agent 1"
```

The agent should be configured to pull from location "EDM1"

FWIW, each agent doesn't need a dedicated location if they are all in the same location and support the same browsers (wasn't sure because of the "agent 1" bit).  Multiple agents can be configured to pull from the same location.

**Comment by sitestress** [comment]
Hi marx, hi Patrick

I had the same problem. If no Browser/Location set (example -> runtest.php?url=www.domain.de), the creation of the default location will fail. the value in the file "testinfo.ini" and "testinfo.json" for "loc="  is not "loc=Testlocation" but "loc=Testlocation:Chrome". As a hotfix I modified in www / runtest.php

_// use the default location if one wasn't specified
            if( !strlen($test['location']) )
            {
                $def = $locations['locations']['default'];
                if( !$def )
                    $def = $locations['locations']['1'];
 $loc = $locations[$locations[$def]['default']]['location'];
  if( !$loc ){
				$loc = $locations[$locations[$def]['1']]['location'];
				}	
                $test['location'] = $loc;
            }
_

instead of

_// use the default location if one wasn't specified
            if( !strlen($test['location']) )
            {
                $def = $locations['locations']['default'];
                if( !$def )
                    $def = $locations['locations']['1'];
                $loc = $locations[$def]['default'];
                if( !$loc )
                    $loc = $locations[$def]['1'];
                $test['location'] = $loc;
            }_


Here is my  location.ini

_[locations]
1=Pasta
default=Pasta

[Pasta]
1=Testlocation
label=EDM Agent 1
group=EDM

[Testlocation]
browser=Chrome,firefox,IE 11
label=All browses - Agent 1
connectivity=Native

_

Regards
karl
