### ISSUE TITLE
Microsoft Edge Support

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/webpagetest#560]
Any plans to support Microsoft Edge? Would be great to have accompany EC2 AMI's for Edge as well although it doesn't look like EC2 support a Windows environment that can actually run it yet.

**Comment by pmeenan** [comment]
Yes, as soon as they ship extension support (though as you've noticed EC2 may not be an option for it for a while).

**Comment by david-poirier-csn** [comment]
I've been unable to get dummynet working in Windows 10, x86 or x64. This could be another obstacle, unless it's just me :)

**Comment by pmeenan** [comment]
It's not just you. I poked around a bit and from what I could find, it looks like MS broke the api that the dummynet driver uses to either enumerate or bind to interfaces (can't remember which) and they mentioned it wasn't used much so may not get fixed :-(
I have built the driver before and may be able to switch the APIs but it may be easier to create a new traffic-shaping driver that uses newer net interfaces (maybe something that doesn't require signing and would work with the newer KVM paravirtual drivers that EC2 uses as well). 





On Mon, Jun 6, 2016 at 8:09 PM -0400, "David Poirier" <notifications@github.com> wrote:












I've been unable to get dummynet working in Windows 10, x86 or x64. This could be another obstacle, unless it's just me :)

**Comment by pmeenan** [comment]
The possibly-related issue I dug up was this: http://stackoverflow.com/questions/32464145/was-compatibility-for-ndis-5-x-drivers-removed-in-windows-10

**Comment by david-poirier-csn** [comment]
So it seems like the choices are to update dummynet to NDIS 6, find a replacement or create a replacement. Updating dummynet is probably the easiest, assuming there's no major changes between NDIS 5 and 6. It is a pain to install though due to the driver signing. 

It seems likely that tools like NetBalancer or NetLimiter use Windows Filtering Platform to throttle individual processes, which would be a nice way to solve this problem. https://msdn.microsoft.com/en-us/library/aa366510%28VS.85%29.aspx

**Comment by pmeenan** [comment]
Yeah.  Not sure I'd add the per-process logic because that may not be available at the packet level which is where you want to do the shaping to get the best accuracy but in looking at the options, a WFP callout driver is probably going to be the best way to go.  Something specific to WPT that only does traffic shaping/loss and doesn't try to handle everything ipfw can do (apply shaping to all traffic with maybe port-based exclusions).

The logic for actually implementing the shaping with a token-based filter (similar to dummynet) is pretty straightforward and I recently did an implementation [here](https://github.com/WPO-Foundation/tsproxy) so there aren't huge technical challenges, just time.

**Comment by Srikanthkumarreddyyekollu** [comment]
we too used ipfw+dummynet in an application and worked fine in Windows 7 but when we tried in in windows 10 its not loading /not recognized.

We badly need help on this or else we need to replace another driver which has same functionality of ipfw ( logging and Rule based )

Please let us know if this issue is fixed.

Srikanth(srikanthkumar.net@gmail.com)

**Comment by david-poirier-csn** [comment]
It looks like all of the code required is in the repo - see https://github.com/WPO-Foundation/webpagetest/tree/master/dist/webpagetest/agent/shaper. If you can clone and build the latest agent you're set.

**Comment by Srikanthkumarreddyyekollu** [comment]
@pmeenan: since we used ipfw+ dummnet already in few windows 7 machines and now going to migrate to Windows 10 it's a great help if you can provide support for Windows 10 machines.

We can take care of driver signing from Symantec.

**Comment by pmeenan** [comment]
@Srikanthkumarreddyyekollu the shaper driver doesn't duplicate all of ipfw's capabilities - it specifically solves the problem of traffic-shaping and replacing the dummynet portions.  The shaper driver code is all [here](https://github.com/WPO-Foundation/win-shaper/tree/master/driver) but it doesn't do any rule-based processing or logging.  For that you'll need to build your own driver, probably based on the [inspect sample](https://github.com/Microsoft/Windows-driver-samples/tree/master/network/trans/inspect).

**Comment by pmeenan** [comment]
@zeman - Edge support is almost done but there is a MAJOR caveat when it comes to the cloud services.  Edge only runs on Windows 10 (not Server 2016) and the cloud services do not let you run client operating systems in the shared VM's (there are some edge cases where you can bring your own license and run on dedicated hardware but that is basically the same as deploying your own machines and I can't provide AMI's for that).

I don't know if EC2 agents supporting Edge will ever be available (at least until you can either run desktop OS's in the cloud or the Edge team adds support for the Server OS's).

For the public instance I will be rolling support out in Dulles over the next week or two but those are machines that I control directly (though the thought that the OS licenses cost significantly more than the hardware saddens me).

**Comment by david-poirier-csn** [comment]
@pmeenan there is an exception to this in Azure - if you have a Visual Studio MSDN subscription (I do) you can create Windows 10 machines. Here's the description:

> This image contains Windows 10 Enterprise N (x64) (Anniversary Update) and is exclusively available to Visual Studio subscribers. It allows you to easily and quickly set up an environment in Azure to develop and test applications targeting Windows 10.Join the Windows Insider Program (https://insider.windows.com/) to receive more frequent, incremental builds of Windows.

Maybe someone at MS can hook you up with a subscription and some credits.

**Comment by pmeenan** [comment]
@david-poirier-csn good to know, thx.  I have an MSDN account and that may work for companies testing their own content.  

The licensing language always makes my head spin and things get confusing around the fact that it is licensed to a specific user and it is not covered for running in a production environment.  It might work for a single person spinning up instances to test the sites that they work on but I'm pretty sure it doesn't cover either @zeman's use case (SpeedCurve) or probably even the public webpagetest.org's use case.

**Comment by Srikanthkumarreddyyekollu** [comment]
Is there any best and easy method to log all ips of destination and source
details in a Windows machine ( it can be a URL browsed or a remote desktop
connection) and also it would be great if we can block few predefined ips.

It shouldn't be a GUI application.
Please suggest.

**Comment by zeman** [comment]
@pmeenan thanks for keeping me in the loop with progress.

**Comment by david-poirier-csn** [comment]
@pmeenan You can also create a custom Windows 10 AMI from a VirtualBox VHD and put it onto EC2 that way. I'm not sure about the licensing there - don't ask, don't tell.

**Comment by soulgalore** [comment]
@nolanlawson is this something you can help out with or check the status? We really want to move away from IE11 and use Edge, preferable without hosting Windows ourself :)
