### ISSUE TITLE
Chrome tests large numbers of block requests are slower than test with the requests in

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#584]
I often block third-parties to understand what impact they're having on a page, but I've noticed page loads get longer in Chrome when there's a large number of block requests.

telegraph.co.uk in Firefox
  http://www.webpagetest.org/result/160205_JB_fc1c78112a10e001d874500285adb534/

telegraph.co.uk in Firefox with 3rd Parties blocked
  http://www.webpagetest.org/result/160205_TE_0352ac18021c35bad63d55526671dca7/

telegraph.co.uk in Chrome with 3rd Parties blocked
  http://www.webpagetest.org/result/160205_GF_2150882829a0d952461aadaa82521306/

From the Chrome waterfall it looks like the overhead of blocking in the extension impacts the test, and the CPU is maxed out (unlike the FF test)

**Comment by pmeenan** [comment]
Enabling blocking (or modifying request headers) in Chrome is exceedingly expensive because it enables the code path that turns on the use of the blocking webrequest extension API (which seems to have gotten even slower in Chrome over time).

It looks like all of your blocks were FQDN's which could potentially be a fast path and be handled at the DNS layer instead.  Unfortunately the block feature allows for blocking a substring anywhere in the URL but if I split the blocking into 2 fields (one for substrings and one for domains) would that meet your needs?  That would match the capability on mobile anyway which can only block at the fqdn level.

**Comment by andydavies** [comment]
Blocking at the fqdn level would most of the needs for this use case - which is to show someone the impact 3rd parties are having on their site's performance (makes a good demo)

I knew Chrome and FF did the blocking differently but while I've delved into the Chrome extension, I've never really looked at the DNS stuff - perhaps it's time I learnt!

There's no rush on this, I filled the issue so it didn't get lost - I've been aware of it for a while but thought others might not be.

**Comment by pmeenan** [comment]
Just rolled out 2 new commands in wptdriver 300 that operate at the DNS level (no overhead).

[blockDomains](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-blockDomains) - Takes a space-delimited list of fqdn's to block

[blockDomainsExcept](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-blockDomainsExcept) - Takes a space-delimited list of fqdn's and blocks anything not on the list (white list).

**Comment by andydavies** [comment]
Thanks Pat, 

I presume this only available the script level rather than the web UI box - as the blocking list can contain wildcards.

Got a half written post about using blocking that I need to finish so will include this too.

**Comment by pmeenan** [comment]
Yes, currently it is only available through scripting but expanding that is trivial and I may try over the weekend (OOTO today).

Going to re-open as there are a few more things I want to do with it:
* Add input fields in the block tab of the UI for the domain black and white lists (and the matching API fields)
* Add mobile agent support for the blockDomains command (since that's effectively what it does for block today)
* Add support for specifying regex's to the domain list i.e. /^.*mydomain\.com$/ (desktop only)

**Comment by pmeenan** [comment]
Finally got a fix in place (and as a bonus got substring-based blocking working on mobile).

No blocking: http://www.webpagetest.org/result/170210_7Y_8f378d76be56e27f3f34cf9f3b30bfc9/

Firefox Blocking: http://www.webpagetest.org/result/170210_GN_12e9b73717fe0f46168218b3f9599e94/

Chrome Blocking: http://www.webpagetest.org/result/170210_41_807bf143d03b9d8b2ad05e222402f1a7/

**Comment by abarre** [comment]
@pmeenan, I'm not sure of the final status of this feature.
Do you confirm that `block` is functional in Chrome or do you advise to use `blockDomains` for Chrome ?

**Comment by pmeenan** [comment]
block ***should*** be functional in Chrome (desktop and mobile) and uses the built-in support with [Network.setBlockedURLs](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setBlockedURLs).  There's been a report or tow of it not working as expected though so I need to make sure it is working.

**Comment by urekxmazino** [comment]
> Just rolled out 2 new commands in wptdriver 300 that operate at the DNS level (no overhead).
> 
> [blockDomains](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-blockDomains) - Takes a space-delimited list of fqdn's to block
> 
> [blockDomainsExcept](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-blockDomainsExcept) - Takes a space-delimited list of fqdn's and blocks anything not on the list (white list).

hi do u mind updating those urls
