### ISSUE TITLE
Viewing Chrome timeline using inspector ignores run paramater

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/webpagetest#619]
When viewing the Chrome timeline using the "view" link that loads the chrome/inspector the run=x query parameter is not passed through to getTimeline.php by the inspector.

Without the run parameter getTimeline.php defaults to run=1 so even if you have multiple runs the inspector always loads the first run.

These two view timeline URLs load the same data.

http://static.webpagetest.org/chrome/inspector-20160510/inspector.html?experiments=true&loadTimelineFromURL=/getTimeline.php?test=160515_G4_TED&run=1&cached=0

http://static.webpagetest.org/chrome/inspector-20160510/inspector.html?experiments=true&loadTimelineFromURL=/getTimeline.php?test=160515_G4_TED&run=2&cached=0

**Comment by pmeenan** [comment]
Argh.  The query param needs to be URLEncoded but it looks like the timeline code doesn't URLDecode the query params.  The real fix is to fix Chrome's timeline viewer to correctly urldecode all of the query params and I opened a bug for that: https://bugs.chromium.org/p/chromium/issues/detail?id=612152

In the meantime, there are 2 possible work-arounds on the WPT side.

1 - Add a rewrite rule and friendly URL scheme for timeline files that avoids ? and & in the URL.  This will only work for sites that have the rewrite rules enabled (and they will need to reload server configs for it to become active).

2 - Instead of using the loadTimelineFromURL support in the inspector code, see if we can trigger the loading from our own JS instead.  This means replacing inspector.html with our own shell instead (it is a trivial file) and seeing if we can call the load operation directly.

I'll take a stab at the second option first since it will work universally but the first is guaranteed to work if I can't make progress (or if the dev tools team lands a fix quickly I can just pick up an updated timeline)

**Comment by pmeenan** [comment]
Hacked around it by encoding all of the options into a single query param.  That avoids having to do any server URL rewrites and works around the timeline URL parsing code issue.
