### ISSUE TITLE
Charging issues with android tablet

### ISSUE THREAD

**Issue by anupdhml** [WPO-Foundation/webpagetest#648]
So this is not a webpagetest issue, but wanted to ask whether people use android tablets for testing.

We have been using nexus 9 with url tests running all day, but because the usb charging is too slow, the tablet runs out of battery and we have to start it again at some point. Has anyone been in a similar situation? Android tablets seem to use USB 2  and looks like this is pretty much unavoidable, but would love to see if there are workarounds.

The tablet is running in the lowest brightness possible and with airplane mode on (but with wifi enabled for testing). We have also tried changing usb ports, cables and host machine, but this is still an issue for us. 

Any suggestions/advice would be much appreciated.

**Comment by pmeenan** [comment]
Have you tried a USB hub that may support a fast charging mode?  I generally use [these](https://www.amazon.com/Upgraded-Anker-SuperSpeed-Including-Charging/dp/B005NGQWL2/ref=sr_1_8?ie=UTF8&qid=1467134483&sr=8-8&keywords=anker+usb+hub) but I've never tried something as big as a Nexus 9.

**Comment by pmeenan** [comment]
btw, it won't help the actual charging but we probably need a feature that checks for battery level and doesn't run tests when it drops below some percentage (like we do with thermal checks).  Not sure that would be enough to get a Nexus 9 to charge back up though.

**Comment by pmeenan** [comment]
Couple of ideas for enhancements:

* Set a minimum allowed battery level for running tests.
    * The battery level can be checked by "adb shell dumpsys battery | grep level"
* Toggle the display off when not running tests.
    * Checking the current display state differs by android version:
        * adb shell dumpsys input_method | grep mScreenOn (< 5.x)
        * adb shell dumpsys display | grep mScreenState (>= 5.x)
    * adb shell input keyevent KEYCODE_POWER (toggles)
    * Combined with the minimum battery level this would guarantee charging when it drops too low

In the short term, you may be able to force the display to turn off but still be active but it is [device specific](http://androidforums.com/threads/backlight-will-not-turn-off.343317/).  On my LG G3 the backlight controls are in /sys/devices/mdp.0/qcom,mdss_fb_primary.175/leds/lcd-backlight.  Using a root shell (adb shell then su) if I "echo 1 > max_brightness" and "echo 0 > brightness" the backlight will turn off but tests still work and video is captured fine.  I kind of like having the display visible though because it lets me watch if a test is working and if a device is online.

If the lowest brightness in the UI is too bright you may also just be able to "echo 1 > brightness" and get a dimmer backlight.

**Comment by anupdhml** [comment]
@pmeenan Thanks so much for the tips! The brightness one is definitely going to help.

For nexus 9, the brightness file was in `/sys/devices/platform/tegra-dsi-backlight.0/backlight/tegra-dsi-backlight.0` and `echo 0 > brightness` reduced it below the level accessible from the android controls.

I am also going to try the usb hub, and a [USB Y cable](https://www.amazon.com/dp/B00NIGO4NM) which will maybe give it more power if the hub fails.

The enhancements you proposed would be good to have and would actually be very helpful if the issue continues for our nexus9 (or other android tablets we might try). When I have some time, I can also work on adding it.

**Comment by anupdhml** [comment]
Just an update: I got the usb hub you recommended and it's working great! The 10th port provides AC charging (and keeps the data connection alive), so battery is all good and our tests are running all the time now. 

Also tried the USB Y cable earlier but that did not help. We don't need it now though.
