### ISSUE TITLE
H2 server pushed resources missing from Canary waterfall

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#666]
Tests using Canary are missing the server-pushed resources.

One the test page the css, js and font are all pushed - they're obviously downloaded at the page renders correctly (and for comparison can be seen in the Chrome waterfall)

**Canary**
http://www.webpagetest.org/result/160715_3W_16a08d4a72dd0252141f90937086dc1e/

**Chrome**
http://www.webpagetest.org/result/160715_ZV_9aa0f5f0d0995a9d074ce2c930e8bbe2/

**Comment by pmeenan** [comment]
Thanks for the heads-up.  My guess is that the SSL hooking in Chrome broke with the latest Canary and it is falling back to dev tools (which doesn't include pushed resources).  It's a little fragile because it does a memory scan of the Chrome binary using some heuristics to identify the TLS entry points for hooking.

Should be easy enough to fix.  I'll take a look on Monday.

**Comment by pmeenan** [comment]
Code is fixed (and tested in dev).  I'll update this when the release agent is pushed later this afternoon (have a few other fixes I want to roll in)

**Comment by pmeenan** [comment]
ok, update has been pushed and is live now: http://www.webpagetest.org/result/160716_37_bb4c40f8a0f04f59453c0a0e46ddfbed/
