### ISSUE TITLE
Get pagespeed data from WPT or HAR

### ISSUE THREAD

**Issue by bajubullet** [WPO-Foundation/webpagetest#669]
Is there an API to get just the pagespeed data from WPT. 

If not I am assuming you are running pagespeed on HAR somehow. Can you please tell me how to do that.

**Comment by pmeenan** [comment]
The PageSpeed scores in WPT have long-since been deprecated and were only available on the old IE agent.  They relied on an old pagespeed c++ library that hasn't been updated in well over 5 years and no longer aligns well with the online version of the tool.

If you are only interested in PageSpeed scores you should use the [PageSpeed Insights API](https://developers.google.com/speed/docs/insights/v2/getting-started) directly.

**Comment by bajubullet** [comment]
Thanks for the reply.

Awesome work !!
