### ISSUE TITLE
Executing jQuery commands in Firefox seems to be broken

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/webpagetest#686]
Let's assume the following script for a page which is working with jQuery:
```
logData	0
navigate	https://api.jquery.com/
exec	$(".searchform input").first().val("foobar")
logData	1
execAndWait	$(".searchform button").click()
```
With Chrome [it works as expected](https://www.webpagetest.org/result/160816_3K_de109ab15f88ad93848c93cfd777ca7a/), measuring the search function of the jQuery API page by manually filling out the search input and clicking the button.

With Firefox [it does not work](https://www.webpagetest.org/result/160816_HZ_cff0ac5015ab8b547abeac9b98d7cebd/). If you watch an agent during the test, you will see that no data is inserted into the form.

However, if you manually open Firefox's developer console and insert the statements, it does work
Also a similiar script with plain Javascript [works in Firefox](https://www.webpagetest.org/result/160816_QK_c3ff8071f54ee3ffdb906864bf289301/).

Any idea why the WPT/jQuery combination doesn't work?

**Comment by pmeenan** [comment]
The Firefox API's for extensions running in the context of the page generally run the JS inside of a sandbox which doesn't give them access to code from the page itself.

Chrome's were generally the same way but the debugger API's let you run code as if it was in the debugging console and in the context of the page which is why they work.  I haven't been able to figure out how to do the same from Firefox (not for a lack of trying).

If you happen to find a way to have an extension in Firefox inject code as if it was running from the dev console I'd be happy to explore fixing it.

**Comment by sburnicki** [comment]
Oh great, I wasn't aware of this as I mostly use plain JS. If I stumble across something I'll let you know. Thanks :)
