### ISSUE TITLE
CPU slices differences from timeline viewer

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/webpagetest#710]
On some tests we're seeing differences between the browser main thread chart rendered via the waterfall chart and directly viewing the Chrome timeline.

Also here's an example from WPT public.

https://www.webpagetest.org/video/compare.php?tests=160912_S5_6F3-r:2-c:0-e:14

I've trimmed off the timeline at 14s to compare them visually. Chrome timeline on top and WPT waterfall underneath.

<img width="783" alt="browser-compare" src="https://cloud.githubusercontent.com/assets/204268/18425299/7af3d044-790c-11e6-843e-c76c205a9e68.png">

You can see they are quite different when you scale and line them up. In other tests we also generally see a lot more scripting time in the timeline viewer than what comes through in WPT.

Are there some functions or other threads that might not be picked up by WPT? Looking at the code it looks like anything unknown should come through as "other".

**Comment by zeman** [comment]
Here's another example from one of our private instance tests. You can see that events match well across both timelines but there's a lot of extra scripting time in the Chrome timeline (top half) which is not showing in the bottom WPT graph.

<img width="1066" alt="timeline-diff" src="https://cloud.githubusercontent.com/assets/204268/18425775/506bd48a-7910-11e6-99f7-2bf2bc8f0c53.png">

The "missing" events are also not included in other views like the Processing Breakdown which is based on the same CPU slice data.

**Comment by pmeenan** [comment]
Are you running a recent version of the server code?  The CPU slice code was heavily rewritten a month or two ago (using a python script that runs against the timeline file).  If I can reproduce it it should be easy enough to fix.

The timeline viewer shows background threads using a crosshatch pattern so that shouldn't be the issue but looking at actual timelines would help.

The example you pointed to on the public instance looks like it is missing a fairly big layout event at the beginning and isn't displaying the "other" time but all of the scripting time looks properly accounted for.

Here it is with all 3 views aligned:

![timeline](https://cloud.githubusercontent.com/assets/444165/18435649/889f05b4-78c2-11e6-974e-10af4ee0a85a.png)

I'll take a look at the missing layout event but it would help for the other cases to know if you are on the latest code.

**Comment by zeman** [comment]
We did a merge from the master branch on 29th Aug, so should be all up to date.

**Comment by pmeenan** [comment]
Found it.  Can you try updating the trace parser python script?

https://github.com/WPO-Foundation/webpagetest/commit/e612ecee4a6abbff36f9124e1d49610fdf5cb678
