### ISSUE TITLE
Pull more data from Chrome timeline JSON

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/webpagetest#722]
Hey Pat,

As discussed at Velocity it would be great to get more detail out of the Chrome timeline JSON for when each resource is parsed and then executed. This extra detail can just be added to jsonResult.php

For bonus points is frames per second also available? If it's possible to scroll the page using scripting and then capture fps to see if there's jank that would be awesome.

**Comment by pmeenan** [comment]
Doing an interactivity test after the page has loaded has been on my TODO list for a while but that's quite a bit of work and needs a separate issue ;-)

**Comment by pmeenan** [comment]
I have a first pass at the parse/execution timing data ready to go.  Attached is a sample output file.  I'm not sure you really want it included with the json result because it can get pretty big (the attached cnn case is 144KB).  It probably makes more sense to have the JSON reference it and have it available as a separate URL.

The file is a dictionary with entries for each thread and a main_thread entry telling you which one is the main thread.

Inside each thread entry is a dictionary that has entries for all of the content (html and js) that had parse/execute time.

Inside each script entry are entries for the different activities (EvaluateScript, v8.compile and FunctionCall) and each one of those is a list of timings.

Each timing entry is an array which is the start and stop time of the event (in ms with usec granularity).

It is worth noting that events can happen inside of other events.  i.e. v8.compile will overlap and be a subset of EvaluateScript and FunctionCall can happen inside of EvaluateScript as well.  Also, as scripts call into other scripts you can have a long-running FunctionCall in something like jquery that calls functions in other scripts and they will have FunctionCall time for the part of time that they are running.  The explicit relationships aren't maintained because that would effectively be duplicating the timeline data and producing flame charts.

A snippet:

```
{"5512:7292": {
  "http://a.postrelease.com/serve/load.js?async=true": {
    "EvaluateScript": [[6769.529, 6873.58]], 
    "FunctionCall": [[8261.823, 8268.729]], 
    "v8.compile": [[6769.551, 6801.274]]}, 
  "http://d2lv4zbk7v5f93.cloudfront.net/esf.js": {
    "EvaluateScript": [[11152.165, 11201.402]], 
    "FunctionCall": [[11621.992, 11622.328], [11674.59, 11675.557], [11675.695, 11788.741], [12084.712, 12092.124], [12094.097, 12094.119], [12215.835, 12217.85], [13271.554, 13271.719]], 
    "v8.compile": [[11152.189, 11159.167]]}, 
  "http://cdn.krxd.net/partnerjs/xdi/proxy.8df9006c5b1da53515379bf3ec2c573a.html": {
    "EvaluateScript": [[12212.208, 12214.825]], 
    "v8.compile": [[12212.225, 12212.699]]}},
"main_thread": "5512:7292"}
```

[1_js_execution.zip](https://github.com/WPO-Foundation/webpagetest/files/498964/1_js_execution.zip)

**Comment by pmeenan** [comment]
OK, Agent 315 is available with the agent-side changes and the web side has also been updated to expose them in the [json](https://www.webpagetest.org/jsonResult.php?test=160928_VJ_2e0149feb2c20f13e6e668077a9625d8) and [xml](https://www.webpagetest.org/xmlResult.php?test=160928_VJ_2e0149feb2c20f13e6e668077a9625d8) results.

The URLs are labeled as "scriptTiming" in the "rawData" section for each run and points to the URL to [download the json](https://www.webpagetest.org/getgzip.php?test=160928_VJ_2e0149feb2c20f13e6e668077a9625d8&file=1_script_timing.json).

**Comment by addyosmani** [comment]
Hey @pmeenan. Sorry to ping an older thread.

I'm trying to run a bulk test and am wondering if there's a way to see the V8 parse/eval time for results in the "Aggregate Statistics" report (or similar - even if available via some other endpoint).

Here's a sample run - I couldn't find script timing in the output formats at the bottom:
https://www.webpagetest.org/result/161109_P9_9RR/

I do know that:

1. It's possible to see v8.compile and EvaluateScript times in individual reports
2. https://www.webpagetest.org/jsonResult.php?test=[REPORT_ID] includes overall script timings for an individual URL's run
3. https://webpagetest.org/getgzip.php?test=[REPORT_ID]&file=1_script_timing.json can give you per script file V8 timings if you request them individually (again for a single URL)

But it's unclear if there's a way to get script timings (overall and/or individual) for bulk test results without writing something custom. Do you know?

**Comment by pmeenan** [comment]
Are you looking for an overall "script" time or do you need compile/evaluate/etc separate?  It should be easy enough to add to the combined page and object data (assuming timelines were captured with the test - and they are by default on mobile devices).  I just need to know specifically what you'd like to see.

In the UI on a per-test basis it shows up in the "[processing breakdown](https://www.webpagetest.org/breakdownTimeline.php?test=161109_3Z_9TZ&run=1)" and on a per-resource basis I think it's only some of the v8 timings where the call-stack reports back to a specific resource.

I can probably add both the "categories" and "events" as columns in the csv which should probably get you what you're looking for.

**Comment by addyosmani** [comment]
Appreciate for the speedy reply! Separate compile/evaluate/etc would be perfect if it would be possible to include them in the combined/object data. The majority of my tests are on mobile devices (but it's good to know I'd otherwise need to ensure timelines are being captured).

> I can probably add both the "categories" and "events" as columns in the csv which should probably get you what you're looking for.

This seems like it would do the trick. Any help here would be hugely appreciated. Thanks Pat!

**Comment by pmeenan** [comment]
OK, I added the low-level events directly but not the aggregates "Scripting", etc.  They are prefixed with a cpu.* in the columns - like cpu.v8.compile, cpu.EvaluateScript and are in both the page-level and requests data.

Quick warning, the columns may move around a bit and may not all be clustered together.  It discovers the columns as it goes through the data so unless the first test has all of the events then some of the cpu.* events may show up grouped further to the right than the rest of them (at some point I may sort them but don't want to break anything that may depend on the known position of the early columns).

**Comment by addyosmani** [comment]
@pmeenan The low-level events alone are hugely valuable in the aggregate reports. Just checked the output and everything appears to be there as expected:

![](https://i.imgur.com/qnuBPgd.jpg)

This is really impressive. I understand the columns may move around and that's completely okay. Most of my research just plucks out column data so any variability should still be fine as long as they have a column heading one can reason through. 

I greatly appreciate you hacking on this over the holidays. You sir, are awesome.

**Comment by addyosmani** [comment]
@pmeenan One quick follow-up question: if I compute the totals of cpu.v8.compile, cpu.EvaluateScript etc in the bulk reports, does this effectively give me aggregate "scripting" time for the page?

**Comment by pmeenan** [comment]
It will give you the aggregate main-thread time.  I have the pre-parse times available for when the background parser actually kicks in (not as frequently as you'd hope) but the reported times are just for main-thread activity.

**Comment by lili21** [comment]
I can't find parse/eval time .
