### ISSUE TITLE
New chrome window after test finished

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/webpagetest#751]
We recently updated one of our agents from a pretty old version of the WPT agent to a recent build.
Now we can observer the following behavior:

After a simple test with chrome, another chrome window is opened. It appears on screenshots of following tests with other browsers and is only killed when another chrome test is run.

The ProcessExplorer reveals that wptdriver.exe is the parent process of chrome. Do you have any idea how or why this happens?

**Comment by pmeenan** [comment]
Can you try 333 and see if it fixes the issue for you?

When the agents go idle after having run one or more Chrome stable tests they will launch Chrome, wait for it to launch and then kill it.  I'm not 100% sure why the "and kill it" part wasn't working in your environment but I just made a change that should make it use the same method that it uses when running another Chrome test so it should be more consistent (sadly, Chrome ignores the "start minimized" flag so my second mitigation of launching it minimized doesn't help.

As for why we launch Chrome after tests have been run, it's complicated....

Chrome 52 introduced a breaking change where you can't load extensions by command-line into stable-channel Chrome builds (at least without a warning dialog that needs to be clicked).  An ugly hack around that is to run Chrome from a symlink directory that makes it look like it is running from a Canary SxS install path which disables the blocking logic (at least for now).  A downside is that it seems to cause auto-updates to break because of the confusion so when testing is done and the agent is idle we launch Chrome from the direct path to reset it's state so auto-updates will continue to work.

**Comment by sburnicki** [comment]
Looks like the issue is resolved with your fix. Thanks for that! 
The workarounds you need to invent to deal with this are incredible :-D but great work :-)
