### ISSUE TITLE
Add support for windows10

### ISSUE THREAD

**Issue by arrowing** [WPO-Foundation/webpagetest#753]
I am not seeing any error when trying to install .INF, but it does not shown ipfw+dummynet check box under LAN properties. Also when i trying ipfw list command by command prompt getting following error:

`1 [main] ipfw 308 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
the public mailing list cygwin@cygwin.com
my_socket failed 2, cannot talk to kernel module
ipfw: socket: No error`

**Comment by pmeenan** [comment]
Good news is that I'm actively working on this right now as part of adding support for Edge.  There is some discussion as to why it broke in Issue #560 but basically Windows 10 has a bug but they aren't fixing it since virtually no drivers other than ipfw use the broken interface :(

It won't be dummynet/ipfw but I'm working on a traffic-shaping driver that uses newer Windows interfaces that should do the same thing (and actually give me the ability to implement different shaping strategies for testing).

It will probably be a few weeks before it is ready to be shipped though.

**Comment by arrowing** [comment]
Thanks your reply so soon.
I also suppose that is windows 10's issuse.
I am looking forward your new solution.
Thanks again. :)

**Comment by pmeenan** [comment]
The new driver is finished and I have the code integrated with the agent but haven't rolled out a new update yet.  I'll probably have an agent binary in a day or two if you want to try that or if you want to wait for a full release it is probably going to be a couple of weeks.

**Comment by arrowing** [comment]
@pmeenan What a big wonderful! I can wait for the next version. Thank you for your disbursement.
Good man, thanks.

**Comment by Srikanthkumarreddyyekollu** [comment]
We too facing same issue. We badly need windows 10 support.

Please share with us. We can also test and use

**Comment by david-poirier-csn** [comment]
It looks like all of the code required is in the repo - see https://github.com/WPO-Foundation/webpagetest/tree/master/dist/webpagetest/agent/shaper. If you can clone and build the latest agent you're set.

**Comment by Srikanthkumarreddyyekollu** [comment]
You mean  ipfw+dummynet  will work on Windows 10 machines as well?
If so Binaries are available to try in Win 10?

Thank you very much.

**Comment by Srikanthkumarreddyyekollu** [comment]
We're using ipfw+dummnet in Windows 7 machines but when we try this in Windows 10 machines the driver didn't load and there is no error as well hence no clue what needs to be done

Really Appreciate if you have any solution.

**Comment by david-poirier-csn** [comment]
ipfw+dummynet does not work in Windows 10 and never will. Patrick wrote win-shaper to replace it, download it [here](https://github.com/WPO-Foundation/win-shaper/releases) and read the blog entry [here](http://calendar.perfplanet.com/2016/testing-with-realistic-networking-conditions/)

**Comment by Srikanthkumarreddyyekollu** [comment]
Hi David,
Thanks for the reply.
If you have details Please help me to know WHY it will not work.

Best,
Srikanth.

**Comment by pmeenan** [comment]
This is an issue tracker for WebPageTest and winShaper is the replacement used by WebPageTest for Windows 8.1+.  It isn't a generic ipfw replacement or a solution to get ipfw working on Windows 10.

@Srikanthkumarreddyyekollu - Discussions around getting ipfw itself to support Windows 10 don't belong here.  I recommend taking it to Stack Overflow or some place similar if you need help finding alternatives.  If you do post a thread somewhere else I'm fine with a link here to direct users looking for similar issues to the location but otherwise the discussion here needs to stay on-topic relative to WebPageTest supporting WIndows 10.

**Comment by Srikanthkumarreddyyekollu** [comment]
Hi Patrick,Sorry for that.Since you used/refer ipfw in some place i thought i can post here as i wasnt sure where to post which you can read and  can help me to find the solution or alternative tools.

I am checking all possible ways to achieve the windows 10 compatibility.
Thanks.
