### ISSUE TITLE
WPT Agent Version 2.19.0.341 Issue

### ISSUE THREAD

**Issue by mkrsinha5** [WPO-Foundation/webpagetest#777]
Our WPT agent was working perfectly with version 2.19.0.340 till yesterday (12/06/2016) 21:10:14 UTC 
AWS region us-east-1 was updated with version 2.19.0.341 at 06/Dec/2016:21:10:31 UTC 
Now WPT agents are not starting.WebPagetest Agent are keep on terminating and launching new instance in every 15 minutes in EC2.default region.
All tests are stuck now.
How can I enforce WPT server to use version 2.19.0.340 (which was working) while launching new Agent?
Any help is appreciated

Here is ngnix access logs
 [06/Dec/2016:21:10:14 +0000] "GET /work/getwork.php?shards=1&reboot=1&location=ap-southeast-2....&winver=6.1&winserver=1&is64bit=1&software=wpt&version=2.19.0.340&ver=340
[06/Dec/2016:21:10:31 +0000] "GET /work/getwork.php?shards=1&reboot=1&location=us-east-1,&winver=6.1&winserver=1&is64bit=1&software=wpt&version=2.19.0.341&ver=341& "WebPagete
st Driver"

**Comment by pmeenan** [comment]
If you go into settings.ini on the server and comment-out the "[agentUpdate](https://github.com/WPO-Foundation/webpagetest/blob/master/www/settings/settings.ini.sample#L118)" entry it will stop automatically pulling agent updates from the public instance.

You'll also need to manually rool back the update in work/update (wptupdate.ini and wptupdate.zip).  You can get 340 from [here](api.webpagetest.org/work/update/bak/wptupdate.zip.340).

It is bizarre that 341 is causing issues and 340 wasn't though because there were only 2 changes and neither was directly in the agent binaries (one was a firefox pref and the other was the trace parser python script).  That said, I think there was a window where the 341 update had the wrong wptupdate.ini version inside of the zip and I wonder if that is causing the issues.  I'll roll out a clean version as 342 in a few minutes.  It might be better to wait for that before turning off updates.

**Comment by mkrsinha5** [comment]
Pat, I would wait for version 342, thank you so much.

**Comment by pmeenan** [comment]
I just pushed 342.  The servers update hourly but you can force yours to check by hitting http://<server>/cron/hourly.php

**Comment by mkrsinha5** [comment]
Let me try

**Comment by mkrsinha5** [comment]
Pat,looks like version 342 worked for us :) thank you so much.Agents seems working now
