### ISSUE TITLE
WinShaper .inf file not included in PI build

### ISSUE THREAD

**Issue by steveworkman** [WPO-Foundation/webpagetest#792]
From the PI instructions, I'm pretty confused as to how winshaper is meant to work with Windows 10.

- There's no .inf file included with the PI build, so it's not an installable thing
- Taking the .inf file from the [winshaper project](https://github.com/WPO-Foundation/win-shaper/tree/master/bin/x64) and trying to install it provides me with no services to install
- Downloading the released binary and running the GUI works for Chrome, Firefox and IE, but not for Edge (related to #789)
- The GUI closes when you close the explorer window that opened it

I'm not sure which of these are bugs and which are features but I'm not sure I'm doing this right. What's the recommended way to use winshaper?

**Comment by pmeenan** [comment]
The inf isn't needed and you shouldn't have to do anything manually.  wptdriver [installs the driver](https://github.com/WPO-Foundation/webpagetest/blob/master/agent/wptdriver/shaper.cpp#L169) and service when it starts up.

If the shaping is working for Chrome and Firefox there shouldn't be any way that it wouldn't also work for Edge.  wptdriver [configures the traffic shaping](https://github.com/WPO-Foundation/webpagetest/blob/master/agent/wptdriver/web_browser.cc#L130) before kicking off the browser-specific logic and it should be the same in all cases.

You shouldn't have to download anything.  There should be a shaper/ directory as part of the agent that has both the 32-bit and 64-bit drivers.

If you run the gui while wptdriver is running there is a chance that the gui will uninstall the service that wptdriver installed so it will stop traffic shaping from working until you stop and re-start wptdriver.  The two (automated tests and the winshaper gui) aren't really meant to run at the same time since both assume they will be the only ones talking to and controlling the driver.

**Comment by steveworkman** [comment]
So, going back to the provided winshaper file, not touching anything, I get this in all browsers (including Chrome and Firefox that worked when the winshaper GUI was open):

`Test Error: Failed to configure IPFW/dummynet. Is it installed?`

Obviously, you can't install ipfw/dummynet, so something isn't right. WPTDriver is being run as admin and should have permissions to do this stuff. Are there any other prerequisites to get the driver installed?

**Comment by pmeenan** [comment]
Can you right-click on shaper/x64/shaper.sys -> properties and see if there is a digital signatures tab (and that it is signed)?

There might have been one release where the driver went out unsigned but I didn't think it made it into the 3.0 release.  That's one thing that comes to mind that might prevent it from installing.

If your server is set to auto-update the agent from the public instance it should pick up the wptdriver 353 which definetly has a signed version of the driver.

**Comment by steveworkman** [comment]
The driver was signed, but not the latest. Getting that seems to have fixed the issue, and now Chrome and Firefox are running happily. Edge starts up but doesn't navigate when connection shaping is on or off. I'll close this one and forget about Edge for a bit
