### ISSUE TITLE
New WPTAgent and iOS devices?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#865]
Hi Pat,
I have a question: we have seen that the iOS devices at WebPageTest.org  times out now and then but if I understand correctly the plan is to move them to the new agent? So there's no need to report the timeouts since you will push a new solution or do you still want them?

Best
Peter

**Comment by pmeenan** [comment]
One bug with the issue to track it would be helpful, at a minimum to make sure the new agent doesn't have the same issue.  It may still persist depending on what the root cause is.  From time to time the devices like to reboot themselves (I think from overheating since it is just the 6 and iPad Mini, not the 5C) so depending on the overall stability of the devices there may still be issues.

**Comment by soulgalore** [comment]
Created it here: https://github.com/WPO-Foundation/webpagetest/issues/871
