### ISSUE TITLE
Agents timing out on high # of concurrent requests

### ISSUE THREAD

**Issue by shanelabs** [WPO-Foundation/webpagetest#877]
It seems that when there's a lot of requests concurrently loaded from 1 server, the agents get stuck and end up timing out.

This case is reproducable across various agents, and whether it's a public or private WPT instance. Here are 2 example runs: 
https://www.webpagetest.org/result/170511_02_1CBB/
https://www.webpagetest.org/result/170514_XS_H6F/

While there are 120+ resources on that page, the agent seems to stop recording after around 45, consistently.

The website listed in those tests loads just fine and triggers the page loaded event in latest version of Chrome on my computer, as well as loading just fine in other page speed tools:
https://gtmetrix.com/reports/www.bosslaser.com/f4HwkgFy
https://tools.pingdom.com/#!/FKQT8/https://www.bosslaser.com

The 'Waterfall' tab of the gtmetrix report shows about 80 concurrent requests at peak. Perhaps this is throwing off WPT agents?

This is my first issue report - let me know what else I can provide to make it more thorough. If this doesn't seem critical, let me know if there are any walkthroughs/resources for setting up a dev environment for WPT agents so that I can attempt a fix myself.

**Comment by pmeenan** [comment]
Looks like it [reproduces](https://www.webpagetest.org/result/170516_Q8_f7f6ff367cacc3f610436cecccb0dc0b/) with [wptagent](https://github.com/WPO-Foundation/wptagent) (the new cross-platform agent) which makes debugging it a lot easier if you want to poke around.

The new agent allows for capturing a [debug log](https://www.webpagetest.org/getgzip.php?test=170516_Q8_f7f6ff367cacc3f610436cecccb0dc0b&file=1_debug.log) from the test.

Whatever is broken is limited to Chrome because [Firefox](https://www.webpagetest.org/result/170516_05_02979184a31241e9cbe1610b6dd0880a/) and [IE 11](https://www.webpagetest.org/result/170516_VV_35e1a8da24448e041147e363b0c6a90a/) both work fine (which may be why other tools don't have an issue depending on what engine they are built on top of).

Looking at the debug log, there is no "Page.loadEventFired" event which means Chrome never fired the onload event (in the test environment).

It loads fine on my desktop with DevTools open and it also appears to [work with traffic-shaping disabled](https://www.webpagetest.org/result/170516_FR_31f6896bba15fea6e6a4280dde0f6920/) so it's possible that there's something timing-related going on (either with the site code or Chrome).

**Comment by pmeenan** [comment]
Chrome's main thread is getting locked up after processing a request:

![image](https://cloud.githubusercontent.com/assets/444165/26120890/4c2537a8-3a40-11e7-9582-653863ea42c7.png)

Main reason I know the thread is locked is that screen shots and response bodies commands from the dev tools interface timeout after the test times out.  I don't know yet if it is something in the page code (js) that is triggering an infinite loop or if there is a deadlock somewhere in Chrome.  Grabbing a trace didn't show anything interesting so I'm trying a debug build of Chrome right now.

**Comment by shanelabs** [comment]
Wow great work Patrick - looks like you're definitely onto something.

And thanks for the tips about Firefox and native traffic shaping, good to know I can fall back on those options if we can't get this figured out in Chrome.

You rock.

**Comment by pmeenan** [comment]
Debug build of Chrome didn't help.  All of the threads are idle and waiting for messages so whatever is going on is more of a state-machine problem and going to be a lot harder to figure out.  The net logs and traces aren't really showing any signs of what is causing it to get held up.

I opened a [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=723643) on the issue but traction may be hard to get.

**Comment by shanelabs** [comment]
Thanks again Patrick - I feel as though you've given this issue beyond the attention it deserves, and since it's a Chrome bug and not WPT I'm going to go ahead and close the issue here. I'll follow the Chrome bug and cross my fingers there's some activity for it, but won't hold my breath.

Thanks a ton.

**Comment by pmeenan** [comment]
Looks like the Chrome bug is tied to some others I've been looking at and is starting to look like a pretty serious bug with the HTTP/2 request management in Chrome so the bug is getting a lot of traction.  You can follow along [here](https://bugs.chromium.org/p/chromium/issues/detail?id=723748).  Thanks for the report because a 100% repro failcase makes it much easier to debug.

**Comment by shanelabs** [comment]
Wow - you weren't kidding, lots of activity yesterday, and they just tagged it as fixed. I'm assuming it'll take a couple weeks before it gets rolled out into a release that'll be used by WPT agents, will keep an eye on it.

Thank you!

**Comment by pmeenan** [comment]
With luck it will be in Chrome 59 which should come out in a couple of weeks.  If not it will be in 60 which comes out 6 weeks after that.  From a measurement perspective the good (or bad) news is that it's a real problem.
