### ISSUE TITLE
Time/date problem on ami-images?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#892]
Hey Pat,
we had a problem this weekend that the TTFB skyrocket on our instance at AWS. I redeployed another agent and I could see the TTFB go down, but then when I checked Chrome and IE gets certificate errors and pages isn't loading. 

I tried to redeploy the agent a couple of times but the same problem.  @gi11es pointed out that it can be a server clock/time problem on the agent.

We use _ami-4a84a220_ for east-1. I can see that the webpagetest.org ec2 instance on that location works, could it be that the clocks get updated and isn't right when the image is newly deployed?

Best
Peter

**Comment by soulgalore** [comment]
No, it doesn't seem to be that, using the same agent get the time using JS, it seems to be correct. I'll just keep this open a little to see if I can understand whats going on.

**Comment by soulgalore** [comment]
This seems to be some certificate problems on our side (thank you netlog!).

**Comment by pmeenan** [comment]
I wonder if it is tied to us blocking [in-band cert updates from Windows](https://github.com/WPO-Foundation/webpagetest/blob/master/agent/wpthook/track_dns.cc#L44).  When that was allowed, intermittently there would be longer load times, particularly on new instances.

Looks like the images were last updated about a year and a half ago.  It might be a good time to create some new images on top of Server 2016 not that we have better traffic shaping available.

**Comment by soulgalore** [comment]
Yes that is probably the problem: @gi11es tried to reproduce on an Windows 7 VM connecting to the server where we got the certificate problem and there it works.

**Comment by pmeenan** [comment]
I'll roll back the blocking but that opens up an interesting question.  If the updates fail because the update server isn't available for some reason (for regular users), would that make the site effectively unavailable?

I'm not sure that intermittent slow results and not detecting the possible failure is better.

**Comment by soulgalore** [comment]
Yes I see your point but the current status (at least for us) is that we can't test at all using Chrome/IE, but I guess that could be solved with a newer aim?

**Comment by pmeenan** [comment]
I just rolled out wptdriver 382 which removes the blocking of the cert updates.

I don't know if you have a way to measure it but watching out for users who can't connect because their Windows itself isn't getting the cert updates could be a problem.  On the server side if you track the count of partially open TLS connections it may give you a bounding size for the issue.

**Comment by soulgalore** [comment]
Thank you @pmeenan for rolling it out, it works now for us. Yes you are right, this is a potential problem, it comes from the GlobalSign problem (and fix) that we had before https://phabricator.wikimedia.org/T148045
