### ISSUE TITLE
Allow setting load metric in /video/view.php

### ISSUE THREAD

**Issue by digitarald** [WPO-Foundation/webpagetest#952]
Similar (or better) than the `end` parameter for `filmstrip.inc.php`.

Useful for fixing recordings with slideshows or animated ads

**Comment by pmeenan** [comment]
It can't be done at view time because the video is already rendered (and the gray is set when the video is rendered).  If you start at the filmstrip, the rendering should inherit the end options used for the filmstrip.

I'm considering adding support for arbitrary metrics to be used for the end (including user timing).  I may need to introduce some fuzz to have it actually stop at the next frame if there is one within ~500ms (i.e. first paint from the browser may be earlier than it actually gets to screen).
