### ISSUE TITLE
Video download in mobile emulation

### ISSUE THREAD

**Issue by dougsillars** [WPO-Foundation/webpagetest#988]
Using Chrome and an emulated browser (as HTTPArchive does), I sometimes see the webpage behave differently than the way it behaves on a true mobile device.

For example, www.aol.com:
If I run it on a Moto G4:
https://www.webpagetest.org/result/171115_10_6c8e5e488a1e0d819c1292cb8801ca52/1/details/#waterfall_view_step1

I see the m3u8 manifest file at request 136, and then no further video requests.

If I run the same test on Chrome - emulating the G4:
https://www.webpagetest.org/result/171115_WX_1dd98b419a47198ff2383c34a61517a1/1/details/#waterfall_view_step1
The same M3u8 manifest is downloaded (request 137), and then I immediately see 2 more manifests for different bitrates (138, 143) and then sequential .ts segments (00001, 00002, etc.) - several MB worth of video.  This indicates to me that the mobile emulation is allowing more video to download than actually happens on a device.

Thanks!

**Comment by pmeenan** [comment]
Chrome Dev Tools [bug filed](https://bugs.chromium.org/p/chromium/issues/detail?id=785983)

cc @paulirish - this probably impacts Lighthouse as well

**Comment by pmeenan** [comment]
From the Chrome team, it sounds like some differences are expected since Android uses OS video playback support and supports HLS.

What I'm trying to track down now is if Android is still preloading the video (or at least some of it) and it just doesn't show up in the waterfall because it is not being loaded by Chrome or if the actual preload behavior is different.

Any chance you have a more stable page that can reproduce it?  I went to grab a tcpdump this morning but it looks like the video is no longer being served and the current one downloads a mp4 on both emulation and real devices.
