### ISSUE TITLE
Firefox potentially downloads Tracking Protection list during page load

### ISSUE THREAD

**Issue by digitarald** [WPO-Foundation/webpagetest#990]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1418013#c7

**Comment by soulgalore** [comment]
We still use the Windows version since we haven't got Linux to work as we want on AWS, so checking the prefs (maybe) we are missing `privacy.trackingprotection.enabled false` (it's there in wpt agent and in https://wiki.mozilla.org/Security/Tracking_protection (if that's the right way to turn it off) but not in the Windows version.

**Comment by pmeenan** [comment]
I disabled it in [wptagent yesterday](https://github.com/WPO-Foundation/wptagent/commit/bc045db617fc7be0c8ddb574fd314f97b8beec34) and in [wptdriver today](https://github.com/WPO-Foundation/webpagetest/commit/4c4a77f33ae303a844e20d10af16d4f9d180a97a)

wptagent already had privacy.trackingprotection.enabled set to false and was still seeing the requests so privacy.trackingprotection.annotate_channels was certainly needed (or one of the other settings - I threw the kitchen sink at it).

Please re-open if you see them come back.
